const tumKategoriler = {
    genel: {
        tr: [
            {soru: "Everest Dağı hangi iki ülkenin sınırında yer alır?", secenekler: ["Nepal ve Çin (Tibet)", "Hindistan ve Pakistan", "İsviçre ve İtalya", "Şili ve Arjantin"], dogru: 0},
            {soru: "Pizza ilk olarak hangi ülkede ve şehirde ortaya çıkmıştır?", secenekler: ["İtalya / Napoli", "Fransa / Paris", "İspanya / Madrid", "Yunanistan / Atina"], dogru: 0},
            {soru: "Dünyanın en derin okyanus çukuru olan Mariana Çukuru nerededir?", secenekler: ["Pasifik (Büyük) Okyanusu", "Atlantik Okyanusu", "Hint Okyanusu", "Arktik Okyanusu"], dogru: 0},
            {soru: "Sushi geleneksel olarak hangi ülkenin mutfağına aittir?", secenekler: ["Japonya", "Çin", "Güney Kore", "Tayland"], dogru: 0},
            {soru: "Dünyanın en uzun nehirleri listesinde birinci sırada yer alan nehir hangisidir?", secenekler: ["Nil Nehri", "Amazon Nehri", "Mississippi Nehri", "Ganj Nehri"], dogru: 0},
            {soru: "Eyfel Kulesi hangi ülkenin başkentinde bulunmaktadır?", secenekler: ["Fransa (Paris)", "İtalya (Roma)", "Almanya (Berlin)", "İngiltere (Londra)"], dogru: 0},
            {soru: "Çin Seddi'nin ana yapım amacı aşağıdakilerden hangisidir?", secenekler: ["Kuzeyden gelen saldırıları önlemek", "Su akışını kontrol etmek", "Ticaret yolu oluşturmak", "Sınırları belirlemek"], dogru: 0},
            {soru: "Dünyanın en büyük yüzölçümüne sahip ülkesi hangisidir?", secenekler: ["Rusya", "Kanada", "Çin", "Amerika Birleşik Devletleri"], dogru: 0},
            {soru: "Kahvenin anavatanı olarak bilinen ve espresso kültürüyle ünlenen ülke neresidir?", secenekler: ["İtalya", "Brezilya", "Kolombiya", "Etiyopya"], dogru: 0},
            {soru: "Güneş sistemindeki en büyük gezegen hangisidir?", secenekler: ["Jüpiter", "Satürn", "Mars", "Neptün"], dogru: 0},
            {soru: "Eyfel Kulesi hangi yıl tamamlanarak ziyarete açılmıştır?", secenekler: ["1889", "1905", "1789", "1923"], dogru: 0},
            {soru: "Mona Lisa tablosunun dünyaca ünlü ressamı kimdir?", secenekler: ["Leonardo da Vinci", "Pablo Picasso", "Vincent van Gogh", "Michelangelo"], dogru: 0},
            {soru: "Hangi gezegen 'Kızıl Gezegen' olarak bilinir?", secenekler: ["Mars", "Venüs", "Jüpiter", "Merkür"], dogru: 0},
            {soru: "Türkiye'nin başkenti neresidir?", secenekler: ["Ankara", "İstanbul", "İzmir", "Bursa"], dogru: 0},
            {soru: "Özgürlük Heykeli hangi ülkenin hediyesi olarak ABD'ye verilmiştir?", secenekler: ["Fransa", "İngiltere", "İtalya", "Almanya"], dogru: 0},
            {soru: "Dünyanın en küçük kıtası hangisidir?", secenekler: ["Avustralya", "Avrupa", "Antarktika", "Güney Amerika"], dogru: 0},
            {soru: "Futbol maçlarında bir takım sahada kaç oyuncuyla yer alır?", secenekler: ["11", "10", "9", "12"], dogru: 0},
            {soru: "Hangi elementin simgesi 'Au'dur?", secenekler: ["Altın", "Gümüş", "Bakır", "Demir"], dogru: 0},
            {soru: "Dünya Sağlık Örgütü'nün kısaltılmış uluslararası ismi nedir?", secenekler: ["WHO", "UNICEF", "NATO", "UNESCO"], dogru: 0},
            {soru: "İnsan vücudundaki en büyük organ hangisidir?", secenekler: ["Deri", "Karaciğer", "Akciğer", "Kalp"], dogru: 0},
            {soru: "Hangi yapı dünyanın yedi harikasından biri olarak kabul edilir?", secenekler: ["Tac Mahal", "Özgürlük Heykeli", "Big Ben", "Sydney Opera Evi"], dogru: 0},
            {soru: "Dünyanın en kalabalık ülkesi hangisidir?", secenekler: ["Hindistan", "Çin", "ABD", "Endonezya"], dogru: 0},
            {soru: "Hangi ülke sıfır (0) rakamını ilk kullanan medeniyete ev sahipliği yapmıştır?", secenekler: ["Hindistan", "Mısır", "Yunanistan", "Roma"], dogru: 0},
            {soru: "Buzulların erimesiyle en çok tehdit altında olan sevimli kutup hayvanı hangisidir?", secenekler: ["Kutup Ayısı", "Kanguru", "Zürafa", "Aslan"], dogru: 0},
            {soru: "Kilometre cinsinden en uzun okyanus hangisidir?", secenekler: ["Pasifik Okyanusu", "Atlantik Okyanusu", "Hint Okyanusu", "Arktik Okyanusu"], dogru: 0},
            {soru: "Hangi ülke pamuk üretiminde dünya çapında önde gelen ülkelerdendir?", secenekler: ["Türkmenistan", "İzlanda", "Norveç", "Yeni Zelanda"], dogru: 0},
            {soru: "Hangi gezegen halkalarıyla (ringen) en çok tanınır?", secenekler: ["Satürn", "Mars", "Venüs", "Merkür"], dogru: 0},
            {soru: "Dünyanın en yüksek şelalesi olan Angel Şelalesi hangi ülkededir?", secenekler: ["Venezuela", "Brezilya", "Kanada", "Güney Afrika"], dogru: 0},
            {soru: "Basketbol oyununun icat edildiği ülke hangisidir?", secenekler: ["Amerika Birleşik Devletleri", "Brezilya", "İspanya", "İtalya"], dogru: 0},
            {soru: "Hangi renk ışık spektrumunda en uzun dalga boyuna sahiptir?", secenekler: ["Kırmızı", "Mavi", "Mor", "Yeşil"], dogru: 0},
            {soru: "Anadolu'nun en eski antik kentlerinden biri olan Efes hangi ilimizdedir?", secenekler: ["İzmir", "Antalya", "Muğla", "Aydın"], dogru: 0},
            {soru: "Dünyanın en büyük çölü olan Sahra Çölü hangi kıtada yer alır?", secenekler: ["Afrika", "Asya", "Avustralya", "Güney Amerika"], dogru: 0},
            {soru: "Hangi ülkenin bayrağında akçaağaç yaprağı bulunur?", secenekler: ["Kanada", "Japonya", "Brezilya", "İsveç"], dogru: 0},
            {soru: "Olimpiyat halkaları kaç renkten ve halkadan oluşur?", secenekler: ["5", "4", "6", "3"], dogru: 0},
            {soru: "Ses hızı havadakinden hangi ortamda daha hızlı yayılır?", secenekler: ["Su ve Katı maddeler", "Boşluk", "Sadece gazlar", "Hava"], dogru: 0},
            {soru: "Hangi organımız kanı filtreleyerek idrarı oluşturur?", secenekler: ["Böbrek", "Karaciğer", "Kalp", "Dalak"], dogru: 0},
            {soru: "Nobel Ödülleri hangi ülkede verilmektedir?", secenekler: ["İsveç", "İsviçre", "Almanya", "Fransa"], dogru: 0},
            {soru: "Dünyanın ilk haritasını çizen ünlü Türk denizci ve bilim insanı kimdir?", secenekler: ["Piri Reis", "Evliya Çelebi", "Barbaros Hayrettin", "Katip Çelebi"], dogru: 0},
            {soru: "Hangi maden elektrik iletkenliğinde en iyisidir?", secenekler: ["Gümüş", "Bakır", "Altın", "Alüminyum"], dogru: 0},
            {soru: "Termometreyi bulan bilim insanı kimdir?", secenekler: ["Galileo Galilei", "Isaac Newton", "Albert Einstein", "Thomas Edison"], dogru: 0},
            {soru: "Hangi kıtada hiç çöl bulunmamaktadır?", secenekler: ["Avrupa", "Asya", "Afrika", "Avustralya"], dogru: 0},
            {soru: "Dünyanın en eski yazılı destanı hangisidir?", secenekler: ["Gılgamış Destanı", "İlyada", "Odysseia", "Şehnâme"], dogru: 0},
            {soru: "Hangi ülke 'Güneşin Doğduğu Ülke' olarak bilinir?", secenekler: ["Japonya", "Çin", "Güney Kore", "İzlanda"], dogru: 0},
            {soru: "Dünya'nın uydusu olan Ay'a ilk ayak basan astronot kimdir?", secenekler: ["Neil Armstrong", "Buzz Aldrin", "Yuri Gagarin", "Michael Collins"], dogru: 0},
            {soru: "Hangi ülkenin bayrağı dikdörtgen olmayan tek bayraktır?", secenekler: ["Nepal", "İsviçre", "Vatikan", "Bhutan"], dogru: 0},
            {soru: "Stratosphere hangi katmandır?", secenekler: ["Atmosfer tabakası", "Okyanus tabakası", "Yer kabuğu", "Mağma tabakası"], dogru: 0},
            {soru: "Dünyanın en tuzlu deniz veya gölü hangisidir?", secenekler: ["Ölü Deniz (Lut Gölü)", "Kızıldeniz", "Hazar Denizi", "Karadeniz"], dogru: 0},
            {soru: "Hangi ülke futbol tarihinde en çok Dünya Kupası kazanmıştır?", secenekler: ["Brezilya", "Almanya", "Arjantin", "İtalya"], dogru: 0},
            {soru: "Ankara Kalesi hangi medeniyet döneminde stratejik amaçla güçlendirilmiştir?", secenekler: ["Galatlar / Roma / Bizans", "Sadece Osmanlı", "Sadece Selçuklu", "Sümerler"], dogru: 0},
            {soru: "Hangi ülkenin başkenti Buenos Aires'tir?", secenekler: ["Arjantin", "Brezilya", "Şili", "Kolombiya"], dogru: 0},
            {soru: "Dünya üzerindeki en büyük mercan resifi sistemi olan Büyük Bariyer Resifi nerededir?", secenekler: ["Avustralya", "Meksika", "Endonezya", "Filipinler"], dogru: 0},
            {soru: "Hangi gaz atmosferde en yüksek oranda bulunur?", secenekler: ["Azot (Nitrojen)", "Oksijen", "Karbondioksit", "Helyum"], dogru: 0},
            {soru: "Türkiye'nin en yüksek dağı olan Ağrı Dağı hangi coğrafi bölgededir?", secenekler: ["Doğu Anadolu", "İç Anadolu", "Karadeniz", "Güneydoğu Anadolu"], dogru: 0},
            {soru: "Hangi antik Roma imparatoru zamanında Roma İmparatorluğu en geniş sınırlarına ulaşmıştır?", secenekler: ["Trajan", "Sezar", "Neron", "Augustus"], dogru: 0},
            {soru: "Matematiğin 'Pi' sayısı yaklaşık olarak hangi değere eşittir?", secenekler: ["3.14", "2.71", "1.61", "1.41"], dogru: 0},
            {soru: "Hangi ülkenin mutfağında 'Sushi' ve 'Ramen' temel yer tutar?", secenekler: ["Japonya", "Çin", "Hindistan", "Tayland"], dogru: 0},
            {soru: "Dünya'nın ekseni etrafındaki bir tam turunu ne kadar sürede tamamlar?", secenekler: ["24 saat", "365 gün", "1 ay", "12 saat"], dogru: 0},
            {soru: "Hangi organımız vücudumuzun dengesini sağlamada kulakla birlikte en önemli görevi üstlenir?", secenekler: ["Beyincik", "Omurilik", "Kalp", "Karaciğer"], dogru: 0},
            {soru: "Uluslararası saat diliminin başlangıç mercii (Greenwich) hangi ülkededir?", secenekler: ["İngiltere", "Fransa", "Almanya", "İtalya"], dogru: 0},
            {soru: "Hangi kıta 'Kara Kıta' olarak anılır?", secenekler: ["Afrika", "Asya", "Antarktika", "Avustralya"], dogru: 0},
            {soru: "Dünya üzerindeki en büyük tatlı su gölü hangisidir?", secenekler: ["Superior Gölü", "Hazar Denizi", "Victoria Gölü", "Michigan Gölü"], dogru: 0},
            {soru: "Hangi ağaç türü yapraklarını dökmeyen iğne yapraklı gruptandır?", secenekler: ["Çam", "Meşe", "Kavak", "Çınar"], dogru: 0},
            {soru: "Hangi ülke ekvator çizgisi üzerinde yer almaz?", secenekler: ["Mısır", "Ekvador", "Endonezya", "Kenya"], dogru: 0},
            {soru: "Anadolu'da kurulan ilk Türk beyliklerinden biri hangisidir?", secenekler: ["Saltuklular", "Osmanlı", "Karamanoğulları", "Dulkadiroğulları"], dogru: 0},
            {soru: "Hangi vitamin güneş ışığı yardımıyla cildimizde sentezlenir?", secenekler: ["D Vitamini", "C Vitamini", "A Vitamini", "B Vitamini"], dogru: 0},
            {soru: "Dünya'nın katmanları arasında en sıcak olan kısım hangisidir?", secenekler: ["İç Çekirdek", "Manto", "Yer Kabuğu", "Dış Çekirdek"], dogru: 0},
            {soru: "Hangi dil dünyada en çok ana dili olarak konuşulan dillerdendir?", secenekler: ["Çince (Mandarin)", "İngilizce", "İspanyolca", "Hintçe"], dogru: 0},
            {soru: "Hangi ülke pirinç üretiminde ve tüketiminde liderlerdendir?", secenekler: ["Çin", "İtalya", "Brezilya", "Arjantin"], dogru: 0},
            {soru: "Hangi medeniyet tekerleği ilk kez icat etmiştir?", secenekler: ["Sümerler", "Mısırlılar", "Romalılar", "Yunanlılar"], dogru: 0},
            {soru: "Hangi coğrafi terim deniz seviyesinden yüksek düzlükleri ifade eder?", secenekler: ["Plato (Ova / Yayla)", "Vadi", "Fiyort", "Delta"], dogru: 0},
            {soru: "Hangi gezegen Güneş'e en yakın gezegendir?", secenekler: ["Merkür", "Venüs", "Mars", "Jüpiter"], dogru: 0},
            {soru: "Hangi ülke kendi adını taşıyan bir yarımada üzerinde kurulmuştur?", secenekler: ["İtalya", "Fransa", "İspanya", "Almanya"], dogru: 0},
            {soru: "Hangi uluslararası kuruluş dünya barışını korumak için 1945'te kurulmuştur?", secenekler: ["Birleşmiş Milletler (BM)", "NATO", "UNESCO", "WHO"], dogru: 0},
            {soru: "Hangi dağ sırası Asya ile Avrupa kıtalarını birbirinden ayırır?", secenekler: ["Ural Dağları", "Alpler", "And Dağları", "Himalayalar"], dogru: 0},
            {soru: "Hangi ülkenin başkenti Moskova'dır?", secenekler: ["Rusya", "Ukrayna", "Belarus", "Polonya"], dogru: 0},
            {soru: "Hangi deniz Avrupa ile Afrika'yı birbirine bağlayan kıtalararası havuzdadır?", secenekler: ["Akdeniz", "Karadeniz", "Baltık Denizi", "Kızıldeniz"], dogru: 0},
            {soru: "Hangi ressam 'Yıldızlı Gece' tablosunu yapmıştır?", secenekler: ["Vincent van Gogh", "Leonardo da Vinci", "Pablo Picasso", "Claude Monet"], dogru: 0},
            {soru: "Hangi ülke kahve çekirdeği ihracatında dünyada ilk sıralardadır?", secenekler: ["Brezilya", "İtalya", "Fransa", "Japonya"], dogru: 0},
            {soru: "Taj Mahal hangi ülkededir?", secenekler: ["Hindistan", "Pakistan", "İran", "Mısır"], dogru: 0},
            {soru: "Optik alanındaki çalışmalarıyla tanınan İslam bilgininin asıl adı nedir?", secenekler: ["İbn-i Heysem", "İbn-i Sina", "Farabi", "Biruni"], dogru: 0},
            {soru: "Dünyanın en büyük okyanusu hangisidir?", secenekler: ["Pasifik", "Atlantik", "Hint", "Arktik"], dogru: 0},
            {soru: "Hangi ülke yüzölçümü olarak dünyanın en küçük ülkesidir?", secenekler: ["Vatikan", "Monako", "San Marino", "Liechtenstein"], dogru: 0},
            {soru: "Güneş'e en uzak olan gezegen hangisidir?", secenekler: ["Neptün", "Uranüs", "Satürn", "Jüpiter"], dogru: 0},
            {soru: "Türkiye'nin kuzeyini çevreleyen deniz hangisidir?", secenekler: ["Karadeniz", "Akdeniz", "Ege Denizi", "Marmara Denizi"], dogru: 0},
            {soru: "Hangi ülkenin başkenti Londra'dır?", secenekler: ["İngiltere", "Fransa", "Almanya", "İtalya"], dogru: 0},
            {soru: "İspanya'nın başkenti neresidir?", secenekler: ["Madrid", "Barselona", "Sevilla", "Valensiya"], dogru: 0},
            {soru: "Fransa'nın başkenti neresidir?", secenekler: ["Paris", "Marsilya", "Lyon", "Nice"], dogru: 0},
            {soru: "Almanya'nın başkenti neresidir?", secenekler: ["Berlin", "Münih", "Frankfurt", "Hamburg"], dogru: 0},
            {soru: "İtalya'nın başkenti neresidir?", secenekler: ["Roma", "Milano", "Venedik", "Napoli"], dogru: 0},
            {soru: "Yunanistan'ın başkenti neresidir?", secenekler: ["Atina", "Selanik", "Rodos", "Patras"], dogru: 0},
            {soru: "Mısır'ın başkenti neresidir?", secenekler: ["Kahire", "İskenderiye", "Giza", "Luxor"], dogru: 0},
            {soru: "Japonya'nın başkenti neresidir?", secenekler: ["Tokyo", "Kyoto", "Osaka", "Hiroşima"], dogru: 0},
            {soru: "Çin'in başkenti neresidir?", secenekler: ["Pekin", "Şanghay", "Hong Kong", "Vuhan"], dogru: 0},
            {soru: "Güney Kore'nin başkenti neresidir?", secenekler: ["Seul", "Busan", "Incheon", "Daegu"], dogru: 0},
            {soru: "Brezilya'nın başkenti neresidir?", secenekler: ["Brasilia", "Rio de Janeiro", "Sao Paulo", "Salvador"], dogru: 0},
            {soru: "Kanada'nın başkenti neresidir?", secenekler: ["Ottawa", "Toronto", "Vancouver", "Montreal"], dogru: 0},
            {soru: "Avustralya'nın başkenti neresidir?", secenekler: ["Kanberra", "Sidney", "Melbourne", "Brisbane"], dogru: 0},
            {soru: "Hindistan'ın başkenti neresidir?", secenekler: ["Yeni Delhi", "Mumbai", "Kalküta", "Bangalore"], dogru: 0},
            {soru: "Meksika'nın başkenti neresidir?", secenekler: ["Meksiko", "Cancun", "Guadalajara", "Puebla"], dogru: 0},
            {soru: "Arjantin'in başkenti neresidir?", secenekler: ["Buenos Aires", "Cordoba", "Rosario", "Mendoza"], dogru: 0}
        ],
        ru: [
            {soru: "На границе каких двух стран находится гора Эверест?", secenekler: ["Непал и Китай (Тибет)", "Индия и Пакистан", "Швейцария и Италия", "Чили и Аргентина"], dogru: 0},
            {soru: "В какой стране и городе появилась пицца?", secenekler: ["Италия / Неаполь", "Франция / Париж", "Испания / Мадрид", "Греция / Афины"], dogru: 0},
            {soru: "Где находится Марианская впадина — самый глубокий океанический желоб?", secenekler: ["Тихий океан", "Атлантический океан", "Индийский океан", "Северный Ледовитый океан"], dogru: 0},
            {soru: "Суши традиционно относятся к кухне какой страны?", secenekler: ["Япония", "Китай", "Южная Корея", "Таиланд"], dogru: 0},
            {soru: "Какая река занимает первое место в списке самых длинных рек мира?", secenekler: ["Нил", "Амазонка", "Миссисипи", "Ганг"], dogru: 0},
            {soru: "В столице какой страны находится Эйфелева башня?", secenekler: ["Франция (Париж)", "Италия (Рим)", "Германия (Берлин)", "Великобритания (Лондон)"], dogru: 0},
            {soru: "Какова была главная цель строительства Великой Китайской стены?", secenekler: ["Предотвращение нападений с севера", "Контроль потока воды", "Создание торгового пути", "Определение границ"], dogru: 0},
            {soru: "Какая страна имеет самую большую площадь в мире?", secenekler: ["Россия", "Канада", "Китай", "США"], dogru: 0},
            {soru: "Какая страна считается родиной эспрессо-культуры?", secenekler: ["Италия", "Бразилия", "Колумбия", "Эфиопия"], dogru: 0},
            {soru: "Какая планета является самой большой в Солнечной системе?", secenekler: ["Юпитер", "Сатурн", "Марс", "Нептун"], dogru: 0},
            {soru: "В каком году была открыта Эйфелева башня?", secenekler: ["1889", "1905", "1789", "1923"], dogru: 0},
            {soru: "Кто написал картину «Мона Лиза»?", secenekler: ["Леонардо да Винчи", "Пабло Пикассо", "Винсент ван Гог", "Микеланджело"], dogru: 0},
            {soru: "Какая планета известна как «Красная планета»?", secenekler: ["Марс", "Венера", "Юпитер", "Меркурий"], dogru: 0},
            {soru: "Какая столица у Турции?", secenekler: ["Анкара", "Стамбул", "Измир", "Бурса"], dogru: 0},
            {soru: "Какая страна подарила США Статую Свободы?", secenekler: ["Франция", "Англия", "Италия", "Германия"], dogru: 0},
            {soru: "Какой материк является самым маленьким по площади?", secenekler: ["Австралия", "Европа", "Антарктида", "Южная Америка"], dogru: 0},
            {soru: "Сколько игроков одной команды одновременно играют на поле в футболе?", secenekler: ["11", "10", "9", "12"], dogru: 0},
            {soru: "Какой химический элемент обозначается как «Au»?", secenekler: ["Золото", "Серебро", "Медь", "Железо"], dogru: 0},
            {soru: "Как расшифровывается ВОЗ на английском?", secenekler: ["WHO", "UNICEF", "NATO", "UNESCO"], dogru: 0},
            {soru: "Какой орган является самым большим у человека?", secenekler: ["Кожа", "Печень", "Легкие", "Сердце"], dogru: 0},
            {soru: "Какая страна является самой густонаселенной в мире?", secenekler: ["Индия", "Китай", "США", "Индонезия"], dogru: 0},
            {soru: "Какая цивилизация впервые использовала число ноль?", secenekler: ["Индия", "Египет", "Греция", "Рим"], dogru: 0},
            {soru: "Какой океан самый большой по площади?", secenekler: ["Тихий океан", "Атлантический", "Индийский", "Северный Ледовитый"], dogru: 0},
            {soru: "Какая планета известна своими кольцами?", secenekler: ["Сатурн", "Марс", "Венера", "Меркурий"], dogru: 0},
            {soru: "В какой стране находится водопад Анхель?", secenekler: ["Венесуэла", "Бразилия", "Канада", "ЮАР"], dogru: 0},
            {soru: "Какая столица у России?", secenekler: ["Москва", "Санкт-Петербург", "Киев", "Минск"], dogru: 0},
            {soru: "Какой газ преобладает в атмосфере Земли?", secenekler: ["Азот", "Кислород", "Углекислый газ", "Гелий"], dogru: 0},
            {soru: "Какая гора является самой высокой в мире?", secenekler: ["Эверест", "Килиманджаро", "Монблан", "Эльбрус"], dogru: 0},
            {soru: "Кто автор картины «Звездная ночь»?", secenekler: ["Винсент ван Гог", "Леонардо да Винчи", "Пабло Пикассо", "Клод Моне"], dogru: 0},
            {soru: "Какая страна является родиной Олимпийских игр?", secenekler: ["Греция", "Италия", "Франция", "Египет"], dogru: 0},
            {soru: "Какая страна является самой большой по площади?", secenekler: ["Россия", "Канада", "Китай", "США"], dogru: 0},
            {soru: "Какая планета ближе всего к Солнцу?", secenekler: ["Меркурий", "Венера", "Земля", "Марс"], dogru: 0},
            {soru: "Какая столица у Франции?", secenekler: ["Париж", "Марсель", "Лион", "Ницца"], dogru: 0},
            {soru: "Какая столица у Италии?", secenekler: ["Рим", "Милан", "Венеция", "Неаполь"], dogru: 0},
            {soru: "Какая столица у Германии?", secenekler: ["Берлин", "Мюнхен", "Франкфурт", "Гамбург"], dogru: 0},
            {soru: "Какая столица у Великобритании?", secenekler: ["Лондон", "Манчестер", "Ливерпуль", "Бирмингем"], dogru: 0},
            {soru: "Какая столица у Испании?", secenekler: ["Мадрид", "Барселона", "Севилья", "Валенсия"], dogru: 0},
            {soru: "Какая столица у Японии?", secenekler: ["Токио", "Киото", "Осака", "Хиросима"], dogru: 0},
            {soru: "Какая столица у Китая?", secenekler: ["Пекин", "Шанхай", "Гонконг", "Ухань"], dogru: 0},
            {soru: "Какая столица у США?", secenekler: ["Вашингтон", "Нью-Йорк", "Лос-Анджелес", "Чикаго"], dogru: 0},
            {soru: "Какая столица у Канады?", secenekler: ["Оттава", "Торонто", "Ванкувер", "Монреаль"], dogru: 0},
            {soru: "Какая столица у Австралии?", secenekler: ["Канберра", "Сидней", "Мельбурн", "Брисбен"], dogru: 0},
            {soru: "Какая столица у Бразилии?", secenekler: ["Бразилиа", "Рио-де-Жанейро", "Сан-Паулу", "Салвадор"], dogru: 0},
            {soru: "Какая столица у Аргентины?", secenekler: ["Буэнос-Айрес", "Кордова", "Росарио", "Мендоса"], dogru: 0},
            {soru: "Какая столица у Египта?", secenekler: ["Каир", "Александрия", "Гиза", "Луксор"], dogru: 0},
            {soru: "Какая столица у Индии?", secenekler: ["Нью-Дели", "Мумбаи", "Калькутта", "Бангалор"], dogru: 0},
            {soru: "Какая столица у Южной Кореи?", secenekler: ["Сеул", "Пусан", "Инчхон", "Тэгу"], dogru: 0},
            {soru: "Какая столица у Мексики?", secenekler: ["Мехико", "Канкун", "Гвадалахара", "Пуэбла"], dogru: 0},
            {soru: "Какая самая длинная река в мире?", secenekler: ["Нил", "Амазонка", "Миссисипи", "Янцзы"], dogru: 0},
            {soru: "Какой океан самый холодный?", secenekler: ["Северный Ледовитый", "Тихий", "Индийский", "Атлантический"], dogru: 0},
            {soru: "Какая пустыня самая большая в мире (жаркая)?", secenekler: ["Сахара", "Гоби", "Атакама", "Калахари"], dogru: 0},
            {soru: "В какой стране находится пирамида Хеопса?", secenekler: ["Египет", "Мексика", "Судан", "Ирак"], dogru: 0},
            {soru: "Кто открыл Америку в 1492 году?", secenekler: ["Христофор Колумб", "Васко да Гама", "Фернан Магеллан", "Марко Поло"], dogru: 0},
            {soru: "Какая страна известна как «Страна восходящего солнца»?", secenekler: ["Япония", "Китай", "Южная Корея", "Вьетнам"], dogru: 0},
            {soru: "Какой химический элемент обозначается как 'O'?", secenekler: ["Кислород", "Водород", "Углерод", "Азот"], dogru: 0},
            {soru: "Какой газ необходим растениям для фотосинтеза?", secenekler: ["Углекислый газ", "Кислород", "Азот", "Гелий"], dogru: 0},
            {soru: "Сколько костей в теле взрослого человека?", secenekler: ["206", "150", "300", "250"], dogru: 0},
            {soru: "Какой металл является жидким при комнатной температуре?", secenekler: ["Ртуть", "Золото", "Железо", "Свинец"], dogru: 0},
            {soru: "Какая планета ближе всего к Земле?", secenekler: ["Венера", "Марс", "Меркурий", "Юпитер"], dogru: 0},
            {soru: "Какая страна имеет форму сапога?", secenekler: ["Италия", "Греция", "Испания", "Португалия"], dogru: 0},
            {soru: "Как называется самая высокая гора в мире?", secenekler: ["Эверест", "Килиманджаро", "Монблан", "Эльбрус"], dogru: 0},
            {soru: "Какой материк самый большой по площади?", secenekler: ["Азия", "Африка", "Северная Америка", "Южная Америка"], dogru: 0},
            {soru: "Какая страна производит больше всего кофе?", secenekler: ["Бразилия", "Колумбия", "Эфиопия", "Вьетнам"], dogru: 0},
            {soru: "Какая планета имеет больше всего спутников?", secenekler: ["Сатурн", "Юпитер", "Уран", "Нептун"], dogru: 0},
            {soru: "Кто написал роман «Война и мир»?", secenekler: ["Лев Толстой", "Федор Достоевский", "Александр Пушкин", "Антон Чехов"], dogru: 0},
            {soru: "Кто написал трагедию «Ромео и Джульетта»?", secenekler: ["Уильям Шекспир", "Мольер", "Гете", "Данте"], dogru: 0},
            {soru: "Какая страна является родиной футбола?", secenekler: ["Англия", "Бразилия", "Германия", "Италия"], dogru: 0},
            {soru: "Сколько игроков в баскетбольной команде на поле?", secenekler: ["5", "6", "7", "4"], dogru: 0},
            {soru: "Сколько очков стоит забитый мяч в кольцо в баскетболе из-за дуги?", secenekler: ["3", "2", "1", "4"], dogru: 0},
            {soru: "Какая национальная валюта в Японии?", secenekler: ["Иена", "Юань", "Вон", "Доллар"], dogru: 0},
            {soru: "Какая национальная валюта в Великобритании?", secenekler: ["Фунт стерлингов", "Евро", "Доллар", "Франк"], dogru: 0},
            {soru: "Какая национальная валюта в США?", secenekler: ["Доллар", "Евро", "Песо", "Фунт"], dogru: 0},
            {soru: "Какой город называют «Городом ангелов»?", secenekler: ["Лос-Анджелес", "Нью-Йорк", "Чикаго", "Майами"], dogru: 0},
            {soru: "Какой город называют «Большим яблоком»?", secenekler: ["Нью-Йорк", "Лос-Анджелес", "Бостон", "Сиэтл"], dogru: 0},
            {soru: "Какая река протекает через Париж?", secenekler: ["Сена", "Темза", "Рейн", "Дунай"], dogru: 0},
            {soru: "Какая река протекает через Лондон?", secenekler: ["Темза", "Сена", "Северный Дон", "Тибр"], dogru: 0},
            {soru: "Какая река протекает через Рим?", secenekler: ["Тибр", "По", "Арно", "Рейн"], dogru: 0},
            {soru: "Какой памятник архитектуры находится в Пизе (Италия)?", secenekler: ["Пизанская башня", "Колизей", "Эйфелева башня", "Биг-Бен"], dogru: 0},
            {soru: "Как называется самый большой океан на Земле?", secenekler: ["Тихий", "Атлантический", "Индийский", "Северный Ледовитый"], dogru: 0},
            {soru: "Какой материк полностью покрыт льдом?", secenekler: ["Антарктида", "Австралия", "Евразия", "Африка"], dogru: 0},
            {soru: "Какой газ преобладает на солнце?", secenekler: ["Водород", "Гелий", "Кислород", "Углерод"], dogru: 0},
            {soru: "Какая часть света состоит из двух материков?", secenekler: ["Америка", "Европа", "Азия", "Океания"], dogru: 0},
            {soru: "Какое животное является символом Австралии?", secenekler: ["Кенгуру", "Панда", "Медведь", "Лев"], dogru: 0},
            {soru: "Какое животное самое быстрое на суше?", secenekler: ["Гепард", "Лев", "Тигр", "Лошадь"], dogru: 0},
            {soru: "Какое животное самое крупное на Земле?", secenekler: ["Синий кит", "Африканский слон", "Жираф", "Белая акула"], dogru: 0},
            {soru: "Какая птица не умеет летать, но отлично плавает?", secenekler: ["Пингвин", "Страус", "Киви", "Эму"], dogru: 0},
            {soru: "Какая птица самая большая в мире?", secenekler: ["Африканский страус", "Кондор", "Альбатрос", "Пеликан"], dogru: 0},
            {soru: "Сколько минут в одном часе?", secenekler: ["60", "100", "24", "30"], dogru: 0},
            {soru: "Сколько часов в сутках?", secenekler: ["24", "12", "48", "60"], dogru: 0},
            {soru: "Сколько дней в обычном невисокосном году?", secenekler: ["365", "366", "360", "364"], dogru: 0},
            {soru: "Сколько месяцев в году?", secenekler: ["12", "10", "6", "24"], dogru: 0},
            {soru: "Какая планета имеет самые заметные кольца?", secenekler: ["Сатурн", "Юпитер", "Нептун", "Марс"], dogru: 0},
            {soru: "Какая звезда ближе всего к Земле?", secenekler: ["Солнце", "Сириус", "Полярная звезда", "Проксима Центавра"], dogru: 0},
            {soru: "Как называется наука о небесных телах?", secenekler: ["Астрономия", "Астрология", "Физика", "Геология"], dogru: 0},
            {soru: "Как называется наука о прошлом человечества?", secenekler: ["История", "География", "Биология", "Химия"], dogru: 0},
            {soru: "Как называется наука о живой природе?", secenekler: ["Биология", "Физика", "Математика", "Астрономия"], dogru: 0},
            {soru: "Какой материк называют «зеленым континентом»?", secenekler: ["Австралия", "Африка", "Южная Америка", "Антарктида"], dogru: 0},
            {soru: "Какой город является столицей Турции?", secenekler: ["Анкара", "Стамбул", "Измир", "Анталья"], dogru: 0},
            {soru: "Какая самая длинная река в Турции?", secenekler: ["Kızılırmak", "Fırat", "Dicle", "Sakarya"], dogru: 0}
        ]
    },
    animasyon: {
        tr: [
            {soru: "DreamWorks yapımı Şrek filminde Şrek'in en yakın geveze dostu hangi hayvandır?", secenekler: ["Eşek (Donkey)", "Kedi", "Köpek", "Ejderha"], dogru: 0},
            {soru: "Kung Fu Panda filmindeki panda Po'nun babası meslek olarak ne iş yapmaktadır?", secenekler: ["Nodul (Çorba) Satıcısı", "Demirci", "Tamirci", "Çiftçi"], dogru: 0},
            {soru: "Madagaskar çizgi filminde hayvanat bahçesinden kaçan ana karakter aslanın adı nedir?", secenekler: ["Alex", "Marty", "Melman", "Gloria"], dogru: 0},
            {soru: "Ejderhanı Nasıl Eğitirsin filmindeki ana ejderha türü hangisidir?", secenekler: ["Gecenin Öfkesi (Toothless)", "Canavar Kabus", "Dehşet Fırtınası", "Ölümcül Nadder"], dogru: 0},
            {soru: "Çizmeli Kedi karakteri ilk olarak hangi DreamWorks film serisinde ortaya çıkmıştır?", secenekler: ["Şrek 2", "Madagaskar", "Kung Fu Panda", "Sevimli Canavarlar"], dogru: 0},
            {soru: "Çizgi film devi DreamWorks stüdyosu hangi yılda kurulmuştur?", secenekler: ["1994", "1985", "2001", "1990"], dogru: 0},
            {soru: "Kötü Çocuklar animasyon filminde çetenin lideri olan hırsız karakter hangi hayvandır?", secenekler: ["Büyük Kötü Kurt", "Köpekbalığı", "Piranha", "Tarantul"], dogru: 0},
            {soru: "Boss Baby (Patron Bebek) şirket çalışanı kılığında aslında neyin peşindedir?", secenekler: ["Köpek sevgisini azaltıp bebek sevgisini artırmak", "Dünyayı ele geçirmek", "Süt fabrikası kurmak", "Oyuncakları yasaklamak"], dogru: 0},
            {soru: "Troller filmindeki prenses Poppy'nin saç rengi hangi renktir?", secenekler: ["Pembe", "Mavi", "Yeşil", "Sarı"], dogru: 0},
            {soru: "Megamind filminde Megamind'ın sadık mavi kafalı balık-robot yardımcısının adı nedir?", secenekler: ["Minion (Prislujnik)", "Robot", "Brain", "Fish"], dogru: 0},
            {soru: "Karlar Ülkesi (Frozen) filmindeki karlar kraliçesinin adı nedir?", secenekler: ["Elsa", "Anna", "Ariel", "Cinderella"], dogru: 0},
            {soru: "Toy Story (Oyuncak Hikayesi) filminde Woody hangi oyuncak türüdür?", secenekler: ["Kovboy bebeği", "Uzay polisi", "Plastik asker", "Kurmalı araba"], dogru: 0},
            {soru: "Arabalar (Cars) filmindeki kahraman yarış arabasının adı nedir?", secenekler: ["Şimşek McQueen", "Mater", "Doc Hudson", "Luigi"], dogru: 0},
            {soru: "Sevimli Canavarlar (Monsters, Inc.) şirketinde çalışan ana karakterlerin adları nelerdir?", secenekler: ["Sulley ve Mike Wazowski", "Shrek ve Eşek", "Tom ve Jerry", "Timon ve Pumbaa"], dogru: 0},
            {soru: "Aslan Kral filminde Simba'nın babasının adı nedir?", secenekler: ["Mufasa", "Scar", "Rafiki", "Zazu"], dogru: 0},
            {soru: "Madagaskar'ın sevimli ve çılgın penguenlerinin lideri kimdir?", secenekler: ["Kaptan (Skipper)", "Kovboy", "Kral Julien", "Mort"], dogru: 0},
            {soru: "Kaptan Düşükdon (Captain Underpants) filmindeki iki haylaz okul öğrencisinin adları nedir?", secenekler: ["George ve Harold", "Tom ve Jerry", "Bart ve Milhouse", "Phineas ve Ferb"], dogru: 0},
            {soru: "Sevimli Tilki karakterinin yer aldığı DreamWorks yapımı animasyon hangisidir?", secenekler: ["Bay Peabody ve Sherman", "Kötü Çocuklar", "Arı Filmi", "Sevimli Canavarlar"], dogru: 0},
            {soru: "Sevimli Arı Filmi'nde (Bee Movie) baş karakter olan arının adı nedir?", secenekler: ["Barry B. Benson", "Buzz", "Stinger", "Flower"], dogru: 0},
            {soru: "Kuzey Kutbu'ndan gelen sihirli koruyucuları konu alan DreamWorks filmi hangisidir?", secenekler: ["Efsane Beşli (Rise of the Guardians)", "Karlar Ülkesi", "Neşeli Ayaklar", "Buz Devri"], dogru: 0},
            {soru: "Ratatuy (Ratatouille) filminde yemek yapma tutkusu olan sevimli farenin adı nedir?", secenekler: ["Remy", "Emile", "Linguini", "Django"], dogru: 0},
            {soru: "Kayıp Balık Nemo filminde Nemo'nun babasının adı nedir?", secenekler: ["Marlin", "Dory", "Bruce", "Crush"], dogru: 0},
            {soru: "İnanılmaz Aile (The Incredibles) filmindeki ailenin en küçük bebeğinin adı nedir?", secenekler: ["Jack-Jack", "Dash", "Violet", "Bob"], dogru: 0},
            {soru: "Yukarı Bak (Up) filmindeki uçan evi binlerce balonla kaldıran sevimli yaşlı amcanın adı nedir?", secenekler: ["Carl Fredricksen", "Russell", "Alpha", "Muntz"], dogru: 0},
            {soru: "Ters Yüz (Inside Out) filminde ana karakter Riley'nin kafasındaki ana duygulardan biri hangisidir?", secenekler: ["Neşe (Joy)", "Bulut", "Rüzgar", "Hız"], dogru: 0},
            {soru: "Minikler (Minions) filminde minionların efendisi olmayı sevdiği en büyük kötü kimdir?", secenekler: ["Scarlet Overkill", "Gru", "Vector", "El Macho"], dogru: 0},
            {soru: "Otel Transilvanya (Hotel Transylvania) filmindeki Drakula'nın kızının adı nedir?", secenekler: ["Mavis", "Erica", "Wanda", "Eunice"], dogru: 0},
            {soru: "Sevimli Hırsızlar (The Bad Guys) filminde yılan karakterin özel yeteneği veya durumu nedir?", secenekler: ["Kilit açma uzmanı kasa hırsızı", "Pilot", "Hacker", "Güçlü kaslı"], dogru: 0},
            {soru: "Kral Şakir çizgi dizisinde Şakir'in babasının adı nedir?", secenekler: ["Remzi", "Kadri", "Necati", "Akbaba"], dogru: 0},
            {soru: "Kral Şakir'in filmlerinde uzaylı veya fantastik olayların çözümünde en çok yardımı dokunan fil masumu karakter kimdir?", secenekler: ["Fil Necati", "Canan", "Miktat", "Şakir"], dogru: 0},
            {soru: "Buz Devri (Ice Age) filmindeki meşe palamudunun peşinden koşan sincabın adı nedir?", secenekler: ["Scrat", "Manny", "Sid", "Diego"], dogru: 0},
            {soru: "Buz Devri filmindeki sevimli ve sakar tembel hayvanın adı nedir?", secenekler: ["Sid", "Diego", "Manny", "Ellie"], dogru: 0},
            {soru: "Çılgın Hırsız (Despicable Me) filminde Gru'nun evlat edindiği üç kız kardeşin en büyüğünün adı nedir?", secenekler: ["Margo", "Edith", "Agnes", "Lucy"], dogru: 0},
            {soru: "Çılgın Hırsız filminde en küçük kız Agnes'in en çok sevdiği oyuncak nedir?", secenekler: ["Peluş Tek Boynuzlu At (Fluffy)", "Ayı", "Araba", "Robot"], dogru: 0},
            {soru: "Şrek 3 filminde Şrek'in kral olmamak için aradığı kuzenin adı nedir?", secenekler: ["Artie (Arthur)", "Fiona", "Prens Charming", "Merlin"], dogru: 0},
            {soru: "Madagaskar 3: Avrupa'nın En Çok Arananları filminde ekibe katılan deniz aslanının adı nedir?", secenekler: ["Stefano", "Gia", "Vitaly", "Duval"], dogru: 0},
            {soru: "Kung Fu Panda 3 filminde Po'nun kendi köyünde bulduğu gerçek babasının adı nedir?", secenekler: ["Li Shan", "Mr. Ping", "Oogway", "Shifu"], dogru: 0},
            {soru: "Ejderhanı Nasıl Eğitirsin 2 filminde Hıçkıdık'ın uzun zamandır kayıp olan annesinin adı nedir?", secenekler: ["Valka", "Astrid", "Stoick", "Gobber"], dogru: 0},
            {soru: "Kırmızı Panda (Turning Red) filminde Mei Lee sinirlendiğinde hangi hayvana dönüşmektedir?", secenekler: ["Dev Kırmızı Panda", "Kahverengi Ayı", "Tilki", "Kaplan"], dogru: 0},
            {soru: "Kımız Büyü (Brave) filminde Prenses Merida'nın okçulukta usta olmasını sağlayan temel özellik nedir?", secenekler: ["Kendi kaderini kendi tayin etme isteği", "Saraydan kaçmak", "Büyü yapmak", "Ejderha yakalamak"], dogru: 0},
            {soru: "Moana filminde okyanusun seçtiği genç kızın adada birlikte yola çıktığı yarı tanrının adı nedir?", secenekler: ["Maui", "Te Fiti", "Tala", "Tui"], dogru: 0},
            {soru: "Coco filminde ana karakter Miguel'in gitmek istediği gizemli yer neresidir?", secenekler: ["Ölüler Diyarı", "Cennet", "Müzik Şehri", "Yeraltı Krallığı"], dogru: 0},
            {soru: "Karlar Ülkesi filminde kardan adam Olaf'ın en büyük hayali nedir?", secenekler: ["Yaz mevsimini yaşamak", "Kışın donmak", "Uçmak", "Denize girmek"], dogru: 0},
            {soru: "Şrek filminde Lord Farquaad'ın yönettiği krallığın adı nedir?", secenekler: ["Duloc", "Far Far Away", "Camelot", "Atlantis"], dogru: 0},
            {soru: "Çizmeli Kedi: Son Dilek filminde kedinin korktuğu amansız avcı kimdir?", secenekler: ["Ölüm (Kurt)", "Altın Kaz", "Jack Horner", "Kitty Patileri"], dogru: 0},
            {soru: "Kötü Çocuklar filminde Bay Piranha hangi özelliğiyle bilinir?", secenekler: ["Şarkı söylemeyi çok sevmesi ve sürpriz yetenekleri", "Sürekli uyuması", "Hiç konuşmaması", "Hızlı koşması"], dogru: 0},
            {soru: "Boss Baby filminde bebeklerin karşı olduğu ana rakip şirket veya kitle kimlerdir?", secenekler: ["Sevimlilik yarışındaki sevimli köpek yavruları", "Kötü robotlar", "Yetişkinler", "Uzaylılar"], dogru: 0},
            {soru: "Troller filminde Bergenlerin mutluluk bulmasının tek yolu nedir?", secenekler: ["Bir Troll yemek", "Dans etmek", "Şarkı söylemek", "Hediye almak"], dogru: 0},
            {soru: "Megamind filminde şehrin kahramanı olan ve sonradan tembelleşen kişinin adı nedir?", secenekler: ["Metro Man", "Titan", "Hal", "Brain"], dogru: 0},
            {soru: "Sevimli Canavarlar filminde çocukların çığlıklarından elde edilen şey nedir?", secenekler: ["Enerji (Elektrik)", "Su", "Altın", "Yakıt"], dogru: 0},
            {soru: "Arabalar 2 filminde Mater ve Şimşek McQueen hangi uluslararası yarışmaya katılırlar?", secenekler: ["Dünya Grand Prix", "Piston Kupası", "Ralli Şampiyonası", "Sokak Yarışı"], dogru: 0},
            {soru: "Toy Story 3 filminde oyuncakların atıldığı tehlikeli yer neresidir?", secenekler: ["Sunnyside Gündüz Bakımevi", "Çöp kutusu", "Müze", "Antika dükkanı"], dogru: 0},
            {soru: "Aslan Kral filminde Timon ve Pumbaa'nın dostlarına öğrettiği hayat felsefesinin adı nedir?", secenekler: ["Hakuna Matata", "Carpe Diem", "Yolo", "Aloha"], dogru: 0},
            {soru: "Madagaskar penguenlerinden Kowalski grupta hangi görevdedir?", secenekler: ["Bilim insanı / Plan yapıcı", "Sürücü", "Ajan", "Aşçı"], dogru: 0},
            {soru: "Kaptan Düşükdon filminde okul müdürünün adı nedir?", secenekler: ["Bay Krupp", "Bay Smith", "Bay Brown", "Bay Teacher"], dogru: 0},
            {soru: "Arı Filmi'nde arıların insanlarla konuşması sonucunda açılan devasa dava kime karşı açılmıştır?", secenekler: ["Bal üreten insan şirketlerine", "Çiçekçilere", "Böcek ilaççılara", "Hükümete"], dogru: 0},
            {soru: "Efsane Beşli filminde Noel Baba'nın kılığındaki karakterin adı nedir?", secenekler: ["Kuzey (North)", "Diş Perisi", "Paskalya Tavşanı", "Jack Frost"], dogru: 0},
            {soru: "Ratatuy filminde eleştirmen Anton Ego'nun yemeği yediğinde çocukluğuna dönmesini sağlayan yemek nedir?", secenekler: ["Ratatouille (Sebze yemeği)", "Çorba", "Pizza", "Makarna"], dogru: 0},
            {soru: "Kayıp Balık Dory'yi Bulmak filminde Dory'nin ailesini ararken unutkanlığıyla ilgili karşılaştığı en büyük zorluk nedir?", secenekler: ["Kısa süreli hafıza kaybı", "Gözünün görmemesi", "Yüzememesi", "Korkması"], dogru: 0},
            {soru: "İnanılmaz Aile filminde baba Bob'un süper gücü nedir?", secenekler: ["Süper Güç / Kuvvet", "Görünmezlik", "Hız", "Esneklik"], dogru: 0},
            {soru: "Yukarı Bak filminde köpeğin konuşmasını sağlayan cihazı kim icat etmiştir?", secenekler: ["Charles Muntz", "Carl", "Russell", "Kevin"], dogru: 0},
            {soru: "Ters Yüz filminde Riley'nin kafasındaki kumanda merkezinden kaybolan iki duygu hangisidir?", secenekler: ["Neşe ve Üzüntü", "Korku ve Öfke", "Öfke ve İğrenme", "Neşe ve Korku"], dogru: 0},
            {soru: "Minikler filminde minionların dili hangi dillerin karışımından oluşturulmuştur?", secenekler: ["İspanyolca, İngilizce, Fransızca, İtalyanca", "Sadece Türkçe", "Sadece Almanca", "Kodlama dilleri"], dogru: 0},
            {soru: "Otel Transilvanya 2 filminde Drakula'nın torunu Dennis'in vampire dönüşüp dönüşmediği ne zaman anlaşılır?", secenekler: ["5. yaş gününde dişleri çıkınca", "Doğduğunda", "Okula başlayınca", "Uçmayı öğrenince"], dogru: 0},
            {soru: "Kral Şakir'de Necati'nin en çok sevdiği yiyecek veya içecek nedir?", secenekler: ["Çay ve börek", "Muz", "Elma", "Hamburger"], dogru: 0},
            {soru: "Buz Devri 4: Kıtasal Kırılma filminde korsanların lideri olan korkunç maymunun adı nedir?", secenekler: ["Kaptan Gutt", "Scrat", "Shira", "Luigi"], dogru: 0},
            {soru: "Çılgın Hırsız 3 filminde Gru'nun uzun süredir haberdar olmadığı ikiz kardeşinin adı nedir?", secenekler: ["Dru", "Balthazar", "El Macho", "Vector"], dogru: 0},
            {soru: "Şrek 2 filminde Çizmeli Kedi'nin süt içerken yaptığı ünlü hareket nedir?", secenekler: ["Kocaman sevimli kedi gözleri bakışı", "Havaya zıplamak", "Patisini yalamak", "Sütü döküvermek"], dogru: 0},
            {soru: "Kung Fu Panda'da Ejderha Savaşçısı'nı seçen bilge kaplumbağa karakterin adı nedir?", secenekler: ["Grand Master Oogway", "Shifu", "Tai Lung", "Lord Shen"], dogru: 0},
            {soru: "Ejderhanı Nasıl Eğitirsin filminde viking köyünün adı nedir?", secenekler: ["Berk", "Vikingistan", "Kuzey Köyü", "Ejderha Adası"], dogru: 0},
            {soru: "Kırmızı Panda filminde Mei'nin arkadaşlarının adlarından biri hangisidir?", secenekler: ["Miriam", "Elsa", "Anna", "Tiana"], dogru: 0},
            {soru: "Cesur (Brave) filminde kraliçe anne büyü yüzünden hangi hayvana dönüşmüştür?", secenekler: ["Ayı", "Kurt", "Kuş", "Tilki"], dogru: 0},
            {soru: "Moana filminde denizin kalbini çalan tanrıça kimdir?", secenekler: ["Te Kā (Te Fiti'nin karanlık hali)", "Maui", "Tala", "Kakamora"], dogru: 0},
            {soru: "Coco filminde Miguel'in büyük büyük büyükbabası olan ünlü müzisyen kimdir?", secenekler: ["Ernesto de la Cruz", "Hector", "Chicharron", "Papa Julio"], dogru: 0},
            {soru: "Karlar Ülkesi 2 filminde ormanda yaşayan gizemli element halkının adı nedir?", secenekler: ["Northuldra halkı", "Elfler", "Cüceler", "Troller"], dogru: 0},
            {soru: "Şrek filminin ilk sinemalara çıkış yılı hangisidir?", secenekler: ["2001", "1999", "2005", "2010"], dogru: 0},
            {soru: "Çizmeli Kedi karakterini orijinal seslendirmede kim seslendirmiştir?", secenekler: ["Antonio Banderas", "Brad Pitt", "Tom Cruise", "Will Smith"], dogru: 0},
            {soru: "Kötü Çocuklar filminde Bay Köpekbalığı hangi konuda yeteneklidir?", secenekler: ["Kılık değiştirme ve ustalık", "Hacker", "Güç", "Hız"], dogru: 0},
            {soru: "Boss Baby filminde bebeğin giydiği takım elbisenin rengi nedir?", secenekler: ["Siyah", "Mavi", "Gri", "Lacivert"], dogru: 0},
            {soru: "Troller filminde Branch (Şube) karakterinin saç rengi aslen hangi renktir?", secenekler: ["Mavi (Sonradan gri/renkli)", "Pembe", "Sarı", "Mor"], dogru: 0},
            {soru: "Megamind filminde süper kahraman Metro Man aslen kimdir?", secenekler: ["Uzaylı", "Robot", "Süper insan", "Büyücü"], dogru: 0},
            {soru: "Sevimli Canavarlar filminde kapıların çalıştığı sistem neye dayanır?", secenekler: ["Dünya çocuklarının dolap kapılarına", "Zaman tüneline", "Uzay gemilerine", "Rüya makinelerine"], dogru: 0},
            {soru: "Arabalar filmindeki Radiator Springs kasabası hangi otoyol üzerindedir?", secenekler: ["Route 66", "Interstate 95", "Route 1", "Highway 10"], dogru: 0},
            {soru: "Toy Story filminde Andy'nin en sevdiği oyuncak kimdir?", secenekler: ["Woody", "Buzz Lightyear", "Rex", "Slinky"], dogru: 0},
            {soru: "Aslan Kral filminde hyena üçlüsünden birinin adı nedir?", secenekler: ["Shenzi", "Mufasa", "Zazu", "Rafiki"], dogru: 0},
            {soru: "Madagaskar filminde zürafa Melman hangi sağlık takıntısına sahiptir?", secenekler: ["Sürekli hasta olduğunu düşünür ve hipokondriaktır", "Karanlıktan korkar", "Su içemez", "Yükseklik korkusu vardır"], dogru: 0},
            {soru: "Kaptan Düşükdon filminde çocukların yazdığı çizgi roman kahramanının adı nedir?", secenekler: ["Kaptan Düşükdon", "Süper Çocuk", "Uçan Adam", "Hızlı Kahraman"], dogru: 0},
            {soru: "Arı Filmi'nde Barry'nin mahkemede savunduğu hak nedir?", secenekler: ["Arıların balını insanların çalmasının durdurulması", "Arılara maaş verilmesi", "Çiçeklerin korunması", "Uçuş serbestliği"], dogru: 0},
            {soru: "Efsane Beşli filminde Jack Frost'un elindeki sihirli değnek veya nesne nedir?", secenekler: ["Buz sopası / Asa", "Kılıç", "Kalkan", "Sihirli lamba"], dogru: 0},
            {soru: "Ratatuy filminde restoranın orijinal kurucusunun adı nedir?", secenekler: ["Chef Gusteau", "Linguini", "Skinner", "Ego"], dogru: 0},
            {soru: "Kayıp Balık Nemo'da Nemo'nun palgegecinde ne tür bir kusur vardır?", secenekler: ["Sağ yüzgeci diğerine göre küçüktür", "Gözü görmez", "Kuyruğu kısadır", "Yüzemez"], dogru: 0},
            {soru: "İnanılmaz Aile filminde anne Helen'in süper kahraman adı nedir?", secenekler: ["Elastigirl (Esnek Kadın)", "İnanılmaz Anne", "Süper Helen", "Hızlı Kadın"], dogru: 0},
            {soru: "Yukarı Bak filminde ev kaç balonla gökyüzüne yükselir?", secenekler: ["Binlerce renkli balonla", "100 balonla", "50 balonla", "10 balonla"], dogru: 0},
            {soru: "Ters Yüz filminde hafıza kürelerinin rengi neyi temsil eder?", secenekler: ["Farklı duyguları", "Zamanı", "Kişileri", "Mekanları"], dogru: 0},
            {soru: "Minikler filminde minionların en sevdiği yiyecek nedir?", secenekler: ["Muz (Banana)", "Elma", "Çikolata", "Dondurma"], dogru: 0},
            {soru: "Otel Transilvanya filminde otelde insan girmesi kesinlikle yasak olan kuralı kim çiğner?", secenekler: ["Jonathan (Johnnny)", "Mavis", "Drakula", "Frankenstein"], dogru: 0},
            {soru: "Kral Şakir'de uzaylılar dünyayı ele geçirmek için neyi kullanır?", secenekler: ["Teknolojik aletler ve akıllı telefon virüsleri", "Büyü", "Işın kılıcı", "Canavarlar"], dogru: 0},
            {soru: "Buz Devri filminde bebek Roshan'ı ailesine ulaştırmaya çalışan ekipte kimler vardır?", secenekler: ["Manny, Sid ve Diego", "Sadece Scrat", "Kroş ve arkadaşları", "Penguenler"], dogru: 0},
            {soru: "Çılgın Hırsız filminde Ay'ı küçültmek için kullanılan silahın adı nedir?", secenekler: ["Küçültme Işını (Shrink Ray)", "Lazer", "Büyük Top", "Mıknatıs"], dogru: 0},
            {soru: "Şrek filminde prenses Fiona'nın üzerine kurulu lanet nedir?", secenekler: ["Geceleri ogre (canavar) oluvermesi", "Hiç konuşamaması", "Uykusuzluk", "Görünmezlik"], dogru: 0}
        ],
		ru: [
			{soru: "Какое животное является лучшим болтливым другом Шрека в одноименном мультфильме от DreamWorks?", secenekler: ["Осел (Donkey)", "Кот", "Собака", "Дракон"], dogru: 0},
			{soru: "Кем работает отец панды По в мультфильме 'Кунг-фу панда'?", secenekler: ["Продавец лапши", "Кузнец", "Механик", "Фермер"], dogru: 0},
			{soru: "Как зовут главного героя-льва, сбежавшего из зоопарка в мультфильме 'Мадагаскар'?", secenekler: ["Алекс", "Марти", "Мелман", "Глория"], dogru: 0},
			{soru: "Какой вид дракона является главным героем в мультфильме 'Как приручить дракона'?", secenekler: ["Ночная Фурия (Беззубик)", "Чудовищный Кошмар", "Громмель", "Смертоносец"], dogru: 0},
			{soru: "В какой серии фильмов DreamWorks впервые появился персонаж Кот в сапогах?", secenekler: ["Шрек 2", "Мадагаскар", "Кунг-фу панда", "Корпорация монстров"], dogru: 0},
			{soru: "В каком году была основана анимационная студия DreamWorks?", secenekler: ["1994", "1985", "2001", "1990"], dogru: 0},
			{soru: "Какое животное является лидером банды грабителей в мультфильме 'Плохие парни'?", secenekler: ["Волк", "Акула", "Пиранья", "Тарантул"], dogru: 0},
			{soru: "Чего на самом деле добивается Босс-молокосос под прикрытием сотрудника компании?", secenekler: ["Уменьшить любовь к щенкам и увеличить к младенцам", "Захватить мир", "Создать молочную фабрику", "Запретить игрушки"], dogru: 0},
			{soru: "Какого цвета волосы у принцессы Розочки (Poppy) из мультфильма 'Тролли'?", secenekler: ["Розовый", "Синий", "Зеленый", "Желтый"], dogru: 0},
			{soru: "Как зовут верного синего робота-помощника Мегамозга в одноименном мультфильме?", secenekler: ["Прислужник (Minion)", "Робот", "Мозг", "Рыбка"], dogru: 0},
			{soru: "Как зовут снежную королеву в мультфильме 'Холодное сердце'?", secenekler: ["Эльза", "Анна", "Ариэль", "Золушка"], dogru: 0},
			{soru: "Каким типом игрушки является Вуди в мультфильме 'История игрушек'?", secenekler: ["Ковбойская кукла", "Космический рейнджер", "Пластиковый солдатик", "Заводная машинка"], dogru: 0},
			{soru: "Как зовут главного героя-гоночную машину в мультфильме 'Тачки'?", secenekler: ["Молния Маккуин", "Мэтр", "Док Хадсон", "Луиджи"], dogru: 0},
			{soru: "Как зовут главных героев, работающих в компании 'Корпорация монстров'?", secenekler: ["Салли и Майк Вазовски", "Шрек и Осел", "Том и Джерри", "Тимон и Пумба"], dogru: 0},
			{soru: "Как зовут отца Симбы в мультфильме 'Король Лев'?", secenekler: ["Муфаса", "Шрам", "Рафики", "Зазу"], dogru: 0},
			{soru: "Кто является лидером милых и сумасшедших пингвинов из Мадагаскара?", secenekler: ["Шкипер (Skipper)", "Ковбой", "Король Джулиан", "Морт"], dogru: 0},
			{soru: "Как зовут двух озорных школьников в мультфильме 'Капитан Подштанник'?", secenekler: ["Джордж и Гарольд", "Том и Джерри", "Барт и Милхаус", "Финес и Ферб"], dogru: 0},
			{soru: "В каком мультфильме DreamWorks появляется персонаж милой лисы?", secenekler: ["Приключения мистера Пибоди и Шермана", "Плохие парни", "Би Муви: Медовый заговор", "Корпорация монстров"], dogru: 0},
			{soru: "Как зовут главного героя-пчелу в мультфильме 'Би Муви: Медовый заговор'?", secenekler: ["Барри Би. Бенсон", "Базз", "Стингер", "Флауэр"], dogru: 0},
			{soru: "Какой мультфильм DreamWorks посвящен магическим хранителям из Северного полюса?", secenekler: ["Хранители снов (Rise of the Guardians)", "Холодное сердце", "Делай ноги", "Ледниковый период"], dogru: 0},
			{soru: "Как зовут милую крысу, мечтающую стать поваром, в мультфильме 'Рататуй'?", secenekler: ["Реми", "Эмиль", "Лингвини", "Джанго"], dogru: 0},
			{soru: "Как зовут отца Немо в мультфильме 'В поисках Немо'?", secenekler: ["Марлин", "Дори", "Брюс", "Краш"], dogru: 0},
			{soru: "Как зовут самого младшего ребенка-супергероя в мультфильме 'Суперсемейка'?", secenekler: ["Джек-Джек", "Дэш", "Фиалка", "Боб"], dogru: 0},
			{soru: "Как зовут пожилого джентльмена, который поднимает дом в небо с помощью тысяч шаров в мультфильме 'Вверх'?", secenekler: ["Карл Фредриксен", "Рассел", "Альфа", "Манц"], dogru: 0},
			{soru: "Какая из основных эмоций живет в голове у Райли в мультфильме 'Головоломка'?", secenekler: ["Радость (Joy)", "Облако", "Ветер", "Скорость"], dogru: 0},
			{soru: "Кем является самый главный злодей, служить которому мечтают миньоны в мультфильме 'Миньоны'?", secenekler: ["Скарлет Оверкилл", "Грю", "Вектор", "Эль Мачо"], dogru: 0},
			{soru: "Как зовут дочь Дракулы в мультфильме 'Монстры на каникулах'?", secenekler: ["Мэвис", "Эрика", "Ванда", "Юнис"], dogru: 0},
			{soru: "Какое особое умение есть у змеи в мультфильме 'Плохие парни'?", secenekler: ["Мастер взлома сейфов", "Пилот", "Хакер", "Силач"], dogru: 0},
			{soru: "Как зовут отца Шакира в мультсериале 'Король Шакир'?", secenekler: ["Ремзи", "Кадри", "Некати", "Акбаба"], dogru: 0},
			{soru: "Какой персонаж-слон больше всех помогает в решении инопланетных или фантастических проблем в фильмах о Короле Шакире?", secenekler: ["Некати", "Джанан", "Микдат", "Шакир"], dogru: 0},
			{soru: "Как зовут белку, которая постоянно охотится за желудем в 'Ледниковом периоде'?", secenekler: ["Скрат", "Мэнни", "Сид", "Диего"], dogru: 0},
			{soru: "Как зовут милого и неуклюжего ленивца из 'Ледникового периода'?", secenekler: ["Сид", "Диего", "Мэнни", "Элли"], dogru: 0},
			{soru: "Как зовут самую старшую из трех девочек, удочеренных Грю в мультфильме 'Гадкий я'?", secenekler: ["Марго", "Эдит", "Агнес", "Люси"], dogru: 0},
			{soru: "Какую игрушку больше всего любит младшая девочка Агнес из мультфильма 'Гадкий я'?", secenekler: ["Плюшевый единорог (Флаффи)", "Мишка", "Машинка", "Робот"], dogru: 0},
			{soru: "Как зовут кузена Шрека, которого тот ищет, чтобы не становиться королем в 'Шрек Третий'?", secenekler: ["Артур (Арти)", "Фиона", "Прекрасный принц", "Мерлин"], dogru: 0},
			{soru: "Как зовут морского льва, присоединившегося к команде в мультфильме 'Мадагаскар 3'?", secenekler: ["Стефано", "Джиа", "Виталий", "Дюбуа"], dogru: 0},
			{soru: "Как зовут настоящего отца По, которого тот находит в своей деревне в 'Кунг-фу панда 3'?", secenekler: ["Ли Шань", "Мистер Пинг", "Угвэй", "Шифу"], dogru: 0},
			{soru: "Как зовут давно потерянную мать Иккинга в мультфильме 'Как приручить дракона 2'?", secenekler: ["Валка", "Астрид", "Стоик", "Плевака"], dogru: 0},
			{soru: "В какое животное превращается Мэй Ли в мультфильме 'Я краснею', когда злится?", secenekler: ["Гигантская красная панда", "Бурый медведь", "Лиса", "Тигр"], dogru: 0},
			{soru: "Что является главной целью принцессы Мериды в мультфильме 'Храбрая сердцем'?", secenekler: ["Самостоятельно выбирать свою судьбу", "Сбежать из дворца", "Заниматься магией", "Ловить драконов"], dogru: 0},
			{soru: "Как зовут полубога, который отправляется в путь вместе с Моаной?", secenekler: ["Мауи", "Те Фити", "Тала", "Туи"], dogru: 0},
			{soru: "Куда хочет попасть главный герой Мигель в мультфильме 'Тайна Коко'?", secenekler: ["Страна мертвых", "Рай", "Город музыки", "Подземное царство"], dogru: 0},
			{soru: "О чем больше всего мечтает снеговик Олаф в мультфильме 'Холодное сердце'?", secenekler: ["О лете", "Замерзнуть зимой", "Летать", "Искупаться в море"], dogru: 0},
			{soru: "Как называется королевство, которым правит лорд Фаркуад в мультфильме 'Шрек'?", secenekler: ["Дюлок", "Далекое-далекое королевство", "Камелот", "Атлантида"], dogru: 0},
			{soru: "Кого боится Кот в сапогах в мультфильме 'Последнее желание'?", secenekler: ["Смерть (Волк)", "Золотой гусь", "Джек Хорнер", "Китти Мягколапка"], dogru: 0},
			{soru: "Чем известна мистер Пиранья из мультфильма 'Плохие парни'?", secenekler: ["Любовью к пению и скрытыми талантами", "Постоянным сном", "Молчаливостью", "Быстрым бегом"], dogru: 0},
			{soru: "Кто является главным конкурентом компании младенцев в мультфильме 'Босс-молокосос'?", secenekler: ["Милые щенки", "Злые роботы", "Взрослые", "Инопланетяне"], dogru: 0},
			{soru: "Какой единственный способ для бергенов обрести счастье в мультфильме 'Тролли'?", secenekler: ["Съесть тролля", "Танцевать", "Петь", "Дарить подарки"], dogru: 0},
			{soru: "Как зовут героя города, который стал ленивым в мультфильме 'Мегамозг'?", secenekler: ["Мачомен (Metro Man)", "Титан", "Хэл", "Мозг"], dogru: 0},
			{soru: "Что получают из детских криков в мультфильме 'Корпорация монстров'?", secenekler: ["Энергию (Электричество)", "Воду", "Золото", "Топливо"], dogru: 0},
			{soru: "В каком международном соревновании участвуют Мэтр и Молния Маккуин в 'Тачках 2'?", secenekler: ["Мировое Гран-при", "Кубок Поршня", "Ралли", "Уличные гонки"], dogru: 0},
			{soru: "Как называется опасное место, куда попадают игрушки в 'Истории игрушек 3'?", secenekler: ["Детский сад 'Солнышко'", "Мусорный бак", "Музей", "Антикварный магазин"], dogru: 0},
			{soru: "Как называется жизненная философия, которой учат Тимон и Пумба в мультфильме 'Король Лев'?", secenekler: ["Акуна Матата", "Carpe Diem", "Yolo", "Алоха"], dogru: 0},
			{soru: "Какую роль выполняет пингвин Ковальски в группе?", secenekler: ["Ученый / Планировщик", "Водитель", "Агент", "Повар"], dogru: 0},
			{soru: "Как зовут директора школы в мультфильме 'Капитан Подштанник'?", secenekler: ["Мистер Крупп", "Мистер Смит", "Мистер Браун", "Мистер Учитель"], dogru: 0},
			{soru: "Против кого был подан иск в мультфильме 'Би Муви' из-за того, что пчелы научились говорить?", secenekler: ["Компаний, производящих мед", "Цветочников", "Производителей пестицидов", "Правительства"], dogru: 0},
			{soru: "Как зовут персонажа в образе Санта-Клауса в мультфильме 'Хранители снов'?", secenekler: ["Северянин (North)", "Зубная фея", "Пасхальный кролик", "Джек Фрост"], dogru: 0},
			{soru: "Какое блюдо возвращает ресторанного критика Антона Эго в детство в мультфильме 'Рататуй'?", secenekler: ["Рататуй", "Суп", "Пицца", "Паста"], dogru: 0},
			{soru: "Какая главная сложность возникает у Дори, когда она ищет свою семью в 'В поисках Дори'?", secenekler: ["Кратковременная потеря памяти", "Проблемы со зрением", "Неумение плавать", "Страх"], dogru: 0},
			{soru: "Какова суперсила отца Боба в мультфильме 'Суперсемейка'?", secenekler: ["Суперсила", "Невидимость", "Скорость", "Гибкость"], dogru: 0},
			{soru: "Кто изобрел устройство, позволяющее собаке говорить в мультфильме 'Вверх'?", secenekler: ["Чарльз Манц", "Карл", "Рассел", "Кевин"], dogru: 0},
			{soru: "Какие две эмоции пропадают из центра управления в мультфильме 'Головоломка'?", secenekler: ["Радость и Печаль", "Страх и Гнев", "Гнев и Брезгливость", "Радость и Страх"], dogru: 0},
			{soru: "Из каких языков был создан язык миньонов?", secenekler: ["Испанский, английский, французский, итальянский", "Только турецкий", "Только немецкий", "Языки программирования"], dogru: 0},
			{soru: "Когда становится понятно, превратился ли Деннис, внук Дракулы, в вампира в 'Монстрах на каникулах 2'?", secenekler: ["На 5-й день рождения, когда выпадают зубы", "При рождении", "При поступлении в школу", "Когда учится летать"], dogru: 0},
			{soru: "Какую еду или напиток больше всего любит Некати в 'Короле Шакире'?", secenekler: ["Чай с буреком", "Банан", "Яблоко", "Гамбургер"], dogru: 0},
			{soru: "Как зовут страшную обезьяну-пирата в мультфильме 'Ледниковый период 4: Континентальный дрейф'?", secenekler: ["Капитан Гатт", "Скрат", "Шира", "Луиджи"], dogru: 0},
			{soru: "Как зовут брата-близнеца Грю, о котором тот долго не подозревал, в 'Гадкий я 3'?", secenekler: ["Дрю", "Бальтазар", "Эль Мачо", "Вектор"], dogru: 0},
			{soru: "Что делает Кот в сапогах, когда пьет молоко в 'Шреке 2'?", secenekler: ["Делает свои знаменитые огромные милые глаза", "Подпрыгивает", "Лижет лапу", "Проливает молоко"], dogru: 0},
			{soru: "Как зовут мудрую черепаху, выбравшую Воина Дракона в 'Кунг-фу панде'?", secenekler: ["Мастер Угвэй", "Шифу", "Тай Лунг", "Лорд Шэнь"], dogru: 0},
			{soru: "Как называется деревня викингов в мультфильме 'Как приручить дракона'?", secenekler: ["Олух (Berk)", "Викингистан", "Северная деревня", "Остров драконов"], dogru: 0},
			{soru: "Как зовут одну из подруг Мэй в мультфильме 'Я краснею'?", secenekler: ["Мириам", "Эльза", "Анна", "Тиана"], dogru: 0},
			{soru: "В какое животное превращается королева-мать из-за магии в 'Храброй сердцем'?", secenekler: ["Медведь", "Волк", "Птица", "Лиса"], dogru: 0},
			{soru: "Кто богиня, у которой украли сердце океана в мультфильме 'Моана'?", secenekler: ["Те Ка (Темная сторона Те Фити)", "Мауи", "Тала", "Какамора"], dogru: 0},
			{soru: "Как зовут знаменитого музыканта, который является прапрадедушкой Мигеля в мультфильме 'Тайна Коко'?", secenekler: ["Эрнесто де ла Крус", "Гектор", "Чичаррон", "Папа Хулио"], dogru: 0},
			{soru: "Как называется народ, живущий в лесу в мультфильме 'Холодное сердце 2'?", secenekler: ["Хульдра (Northuldra)", "Эльфы", "Гномы", "Тролли"], dogru: 0},
			{soru: "В каком году вышел первый мультфильм 'Шрек'?", secenekler: ["2001", "1999", "2005", "2010"], dogru: 0},
			{soru: "Кто озвучил Кота в сапогах в оригинале?", secenekler: ["Антонио Бандерас", "Брэд Питт", "Том Круз", "Уилл Смит"], dogru: 0},
			{soru: "В чем талантлив мистер Акула из мультфильма 'Плохие парни'?", secenekler: ["Маскировка и мастерство", "Хакерство", "Сила", "Скорость"], dogru: 0},
			{soru: "Какого цвета костюм, который носит младенец в 'Босс-молокососе'?", secenekler: ["Черный", "Синий", "Серый", "Темно-синий"], dogru: 0},
			{soru: "Какого цвета волосы у Бранча (Цветан) из мультфильма 'Тролли' изначально?", secenekler: ["Синий (позже серый/цветной)", "Розовый", "Желтый", "Фиолетовый"], dogru: 0},
			{soru: "Кем на самом деле является супергерой Метромен в мультфильме 'Мегамозг'?", secenekler: ["Пришелец", "Робот", "Суперчеловек", "Маг"], dogru: 0},
			{soru: "На чем основана система дверей в мультфильме 'Корпорация монстров'?", secenekler: ["Шкафы детей по всему миру", "Туннель времени", "Космические корабли", "Машины снов"], dogru: 0},
			{soru: "На какой трассе находится город Радиатор-Спрингс из мультфильма 'Тачки'?", secenekler: ["Шоссе 66 (Route 66)", "Interstate 95", "Route 1", "Highway 10"], dogru: 0},
			{soru: "Какая игрушка самая любимая у Энди в 'Истории игрушек'?", secenekler: ["Вуди", "Базз Лайтер", "Рекс", "Слинки"], dogru: 0},
			{soru: "Как зовут одну из гиен в мультфильме 'Король Лев'?", secenekler: ["Шензи", "Муфаса", "Зазу", "Рафики"], dogru: 0},
			{soru: "Какой страх за своим здоровьем есть у жирафа Мелмана в мультфильме 'Мадагаскар'?", secenekler: ["Ипохондрия (постоянно думает, что болен)", "Боязнь темноты", "Не может пить воду", "Боязнь высоты"], dogru: 0},
			{soru: "Как зовут героя комикса, который пишут дети в мультфильме 'Капитан Подштанник'?", secenekler: ["Капитан Подштанник", "Супермальчик", "Летающий человек", "Быстрый герой"], dogru: 0},
			{soru: "Какое право отстаивает Барри в суде в мультфильме 'Би Муви'?", secenekler: ["Прекращение воровства меда людьми", "Выплата зарплаты пчелам", "Защита цветов", "Свобода полета"], dogru: 0},
			{soru: "Какой магический предмет есть у Джека Фроста в руках в 'Хранителях снов'?", secenekler: ["Ледяной посох", "Меч", "Щит", "Волшебная лампа"], dogru: 0},
			{soru: "Как зовут первоначального основателя ресторана в мультфильме 'Рататуй'?", secenekler: ["Шеф Гюсто", "Лингвини", "Скиннер", "Эго"], dogru: 0},
			{soru: "Какой дефект есть у плавника Немо в 'В поисках Немо'?", secenekler: ["Правый плавник меньше левого", "Плохое зрение", "Короткий хвост", "Не умеет плавать"], dogru: 0},
			{soru: "Как зовут супергероиню маму Хелен в мультфильме 'Суперсемейка'?", secenekler: ["Эластика (Elastigirl)", "Супермама", "Супер Хелен", "Быстрая женщина"], dogru: 0},
			{soru: "Сколько шаров нужно, чтобы поднять дом в небо в мультфильме 'Вверх'?", secenekler: ["Тысячи разноцветных шаров", "100 шаров", "50 шаров", "10 шаров"], dogru: 0},
			{soru: "Что представляют собой цвета шариков памяти в мультфильме 'Головоломка'?", secenekler: ["Разные эмоции", "Время", "Людей", "Места"], dogru: 0},
			{soru: "Какую еду больше всего любят миньоны в мультфильме 'Миньоны'?", secenekler: ["Банан", "Яблоко", "Шоколад", "Мороженое"], dogru: 0},
			{soru: "Кто нарушает правило, согласно которому людям строго запрещено входить в отель в 'Монстрах на каникулах'?", secenekler: ["Джонатан (Джонни)", "Мэвис", "Дракула", "Франкенштейн"], dogru: 0},
			{soru: "Что используют инопланетяне, чтобы захватить мир в 'Короле Шакире'?", secenekler: ["Технологические гаджеты и вирусы для смартфонов", "Магию", "Лазерный меч", "Монстров"], dogru: 0},
			{soru: "Кто входит в команду, которая пытается доставить ребенка Рошана семье в 'Ледниковом периоде'?", secenekler: ["Мэнни, Сид и Диего", "Только Скрат", "Крош и друзья", "Пингвины"], dogru: 0},
			{soru: "Как называется оружие, используемое для уменьшения Луны в мультфильме 'Гадкий я'?", secenekler: ["Уменьшитель (Shrink Ray)", "Лазер", "Большая пушка", "Магнит"], dogru: 0},
			{soru: "Какое проклятие наложено на принцессу Фиону в мультфильме 'Шрек'?", secenekler: ["Превращение в огра по ночам", "Неспособность говорить", "Бессонница", "Невидимость"], dogru: 0}
		]
    },
    film: {
		tr: [
			{soru: "The Matrix filminde Neo'nun seçtiği hapın rengi nedir?", secenekler: ["Kırmızı", "Mavi", "Yeşil", "Sarı"], dogru: 0},
			{soru: "Titanik filmindeki başrol erkek karakterin adı nedir?", secenekler: ["Jack", "Rose", "Cal", "Fabrizio"], dogru: 0},
			{soru: "Yüzüklerin Efendisi serisinde 'Tek Yüzük'ü yok etmekle görevli olan karakter kimdir?", secenekler: ["Frodo Baggins", "Gandalf", "Aragorn", "Legolas"], dogru: 0},
			{soru: "Harry Potter serisindeki okulun adı nedir?", secenekler: ["Hogwarts", "Durmstrang", "Beauxbatons", "Ilvermorny"], dogru: 0},
			{soru: "Başlangıç (Inception) filminde rüya içinde rüya kurma teknolojisini yöneten karakteri kim canlandırmıştır?", secenekler: ["Leonardo DiCaprio", "Brad Pitt", "Tom Hardy", "Christian Bale"], dogru: 0},
			{soru: "Star Wars (Yıldız Savaşları) filminde Darth Vader'ın asıl adı nedir?", secenekler: ["Anakin Skywalker", "Luke Skywalker", "Obi-Wan", "Han Solo"], dogru: 0},
			{soru: "Geleceğe Dönüş (Back to the Future) filmindeki zaman makinesi hangi araçtır?", secenekler: ["DeLorean", "Ferrari", "Porsche", "Bisiklet"], dogru: 0},
			{soru: "Gladyatör filminde Maximus'u canlandıran oyuncu kimdir?", secenekler: ["Russell Crowe", "Brad Pitt", "Mel Gibson", "Tom Cruise"], dogru: 0},
			{soru: "Jurassic Park filminde ilk olarak hangi tür dinozorla karşılaşırlar?", secenekler: ["Brachiosaurus", "T-Rex", "Velociraptor", "Triceratops"], dogru: 0},
			{soru: "Dövüş Kulübü (Fight Club) filminin ünlü kuralı nedir?", secenekler: ["Dövüş kulübü hakkında konuşma", "Kavga etme", "Kazanmak için oyna", "Sırrını sakla"], dogru: 0},
			{soru: "Baba (The Godfather) filminde Corleone ailesinin babasının lakabı nedir?", secenekler: ["Don Vito", "Michael", "Sonny", "Fredo"], dogru: 0},
			{soru: "Terminatör filmindeki robotu kim canlandırmıştır?", secenekler: ["Arnold Schwarzenegger", "Sylvester Stallone", "Jean-Claude Van Damme", "Bruce Willis"], dogru: 0},
			{soru: "Esaretin Bedeli (The Shawshank Redemption) filmi nerede geçmektedir?", secenekler: ["Hapishane", "Okul", "Hastanede", "Fabrikada"], dogru: 0},
			{soru: "Yedi (Se7en) filminde katil hangi konuyu temel alarak cinayet işlemektedir?", secenekler: ["Yedi ölümcül günah", "Burçlar", "Haftanın günleri", "Mevsimler"], dogru: 0},
			{soru: "Akıl Defteri (Memento) filminin en belirgin özelliği nedir?", secenekler: ["Ters kronolojik akış", "Tamamı siyah beyaz", "Sesiz film", "Uzayda geçmesi"], dogru: 0},
			{soru: "Pulp Fiction filminin yönetmeni kimdir?", secenekler: ["Quentin Tarantino", "Martin Scorsese", "Steven Spielberg", "Christopher Nolan"], dogru: 0},
			{soru: "Batman (Kara Şövalye) filminde Joker karakterini kim canlandırmıştır?", secenekler: ["Heath Ledger", "Jack Nicholson", "Jared Leto", "Joaquin Phoenix"], dogru: 0},
			{soru: "Forrest Gump filminde karakterin koştuğu ünlü sporda neye odaklanır?", secenekler: ["Amerikan futbolu", "Basketbol", "Beyzbol", "Tenis"], dogru: 0},
			{soru: "Esaslı (Leon: The Professional) filminde kiralık katilin yanında koruduğu kızın adı nedir?", secenekler: ["Mathilda", "Leon", "Stansfield", "Tony"], dogru: 0},
			{soru: "Matrix filminde Morpheus karakterini kim canlandırmıştır?", secenekler: ["Laurence Fishburne", "Keanu Reeves", "Hugo Weaving", "Carrie-Anne Moss"], dogru: 0},
			{soru: "Yüzüklerin Efendisi'nde Gandalf'ın lakabı nedir?", secenekler: ["Gri/Ak Büyücü", "Kral", "Savaşçı", "Hükümdar"], dogru: 0},
			{soru: "Interstellar filminde uzay aracının adı nedir?", secenekler: ["Endurance", "Apollo", "Discovery", "Voyager"], dogru: 0},
			{soru: "Avatar filmindeki gezegenin adı nedir?", secenekler: ["Pandora", "Mars", "Satürn", "Dünya"], dogru: 0},
			{soru: "Şeylerin Doğası (The Truman Show) filminde Truman'ın yaşadığı kasaba aslında nedir?", secenekler: ["Dev bir stüdyo", "Gerçek bir ada", "Bir hapishane", "Bir rüya"], dogru: 0},
			{soru: "Sıkı Dostlar (Goodfellas) filmindeki ana karakterin adı nedir?", secenekler: ["Henry Hill", "Tommy DeVito", "Jimmy Conway", "Paulie"], dogru: 0},
			{soru: "Gladyatör filmindeki kötü imparatorun adı nedir?", secenekler: ["Commodus", "Marcus", "Julius", "Augustus"], dogru: 0},
			{soru: "Yıldız Savaşları'nda 'Güç'ün karanlık tarafını temsil eden güç nedir?", secenekler: ["Sith", "Jedi", "İmparatorluk", "Asi"], dogru: 0},
			{soru: "The Shining (Cinnet) filmindeki otelin adı nedir?", secenekler: ["Overlook", "Grand", "Hilton", "Bates"], dogru: 0},
			{soru: "Zindan Adası (Shutter Island) filminde Leonardo DiCaprio'nun karakteri ne iş yapmaktadır?", secenekler: ["Federal Ajan", "Dedektif", "Doktor", "Hücrede kalan"], dogru: 0},
			{soru: "Rocky filminde baş karakterin lakabı nedir?", secenekler: ["İtalyan Aygırı", "Şampiyon", "Yumruk", "Aslan"], dogru: 0},
			{soru: "Jaws filmindeki canavar nedir?", secenekler: ["Köpekbalığı", "Timsah", "Balina", "Ahtapot"], dogru: 0},
			{soru: "E.T. filminde uzaylının dünyaya geldiğinde saklandığı yer neresidir?", secenekler: ["Bir çocuğun dolabı", "Garaj", "Orman", "Okul"], dogru: 0},
			{soru: "Blade Runner filmindeki 'replicant' nedir?", secenekler: ["Yapay insan", "Uzaylı", "Hayalet", "Robot"], dogru: 0},
			{soru: "The Prestige (Prestij) filminde iki sihirbazın rekabeti hangi dönemi yansıtır?", secenekler: ["Viktorya dönemi", "Modern dönem", "Orta Çağ", "Gelecek"], dogru: 0},
			{soru: "Harry Potter'da asaların çekirdeğinde ne bulunur?", secenekler: ["Anka tüyü / Ejderha yüreği teli", "Altın", "Elmas", "Gümüş"], dogru: 0},
			{soru: "Sessiz Bir Yer (A Quiet Place) filminde yaratıklar neye duyarlıdır?", secenekler: ["Sese", "Işığa", "Kokuya", "Isıya"], dogru: 0},
			{soru: "John Wick filminde baş karakteri kim canlandırmaktadır?", secenekler: ["Keanu Reeves", "Brad Pitt", "Tom Hardy", "Ryan Gosling"], dogru: 0},
			{soru: "Parasite (Parazit) filmi hangi ülkenin yapımıdır?", secenekler: ["Güney Kore", "Japonya", "Çin", "Tayland"], dogru: 0},
			{soru: "Joker (2019) filminde Arthur Fleck'in çalıştığı iş nedir?", secenekler: ["Palyaço", "Komedyen", "Garson", "Muhasebeci"], dogru: 0},
			{soru: "Mad Max: Fury Road filminde karakterin kullandığı aracın ana amacı nedir?", secenekler: ["Hayatta kalmak / Kaçmak", "Yarışmak", "Savaşmak", "Gezmek"], dogru: 0},
			{soru: "Logan filminde Wolverine karakterini son kez kim oynamıştır?", secenekler: ["Hugh Jackman", "Ryan Reynolds", "Christian Bale", "Henry Cavill"], dogru: 0},
			{soru: "Whiplash filminde baş karakter hangi enstrümanı çalmaktadır?", secenekler: ["Bateri", "Piyano", "Gitar", "Keman"], dogru: 0},
			{soru: "The Wolf of Wall Street filminde Jordan Belfort'u kim canlandırır?", secenekler: ["Leonardo DiCaprio", "Matthew McConaughey", "Jonah Hill", "Brad Pitt"], dogru: 0},
			{soru: "Gravity filminde Sandra Bullock karakteri nerede mahsur kalır?", secenekler: ["Uzayda", "Okyanusta", "Çölde", "Dağda"], dogru: 0},
			{soru: "Spotlight filmi neyi araştırmaktadır?", secenekler: ["Kilisedeki istismar skandalı", "Politik yolsuzluk", "Cinayet", "Hırsızlık"], dogru: 0},
			{soru: "Birdman filminde karakterin geçmişteki en ünlü rolü nedir?", secenekler: ["Süper kahraman", "Polis", "Kral", "Katil"], dogru: 0},
			{soru: "Her filminde ana karakter kiminle aşık olur?", secenekler: ["Yapay zeka", "Bir insan", "Bir robot", "Kendisiyle"], dogru: 0},
			{soru: "Arrival filminde dünyaya gelen uzaylılar nasıl iletişim kurar?", secenekler: ["Sembollerle", "Sesle", "Işıkla", "Düşünceyle"], dogru: 0},
			{soru: "La La Land filminde ana karakterlerin meslekleri nelerdir?", secenekler: ["Oyuncu ve caz piyanisti", "Dansçı ve şarkıcı", "Yazar ve ressam", "Doktor ve hemşire"], dogru: 0},
			{soru: "Grand Budapest Hotel filminin yönetmeni kimdir?", secenekler: ["Wes Anderson", "Quentin Tarantino", "Christopher Nolan", "Martin Scorsese"], dogru: 0},
			{soru: "12 Angry Men (12 Öfkeli Adam) filmi nerede geçer?", secenekler: ["Jüri odası", "Mahkeme salonu", "Hapishane", "Polis merkezi"], dogru: 0},
			{soru: "Casablanca filmi nerede geçer?", secenekler: ["Fas", "Fransa", "Almanya", "İspanya"], dogru: 0},
			{soru: "Psiko (Psycho) filminde meşhur sahne nerede geçer?", secenekler: ["Duşta", "Mutfakta", "Bahçede", "Garajda"], dogru: 0},
			{soru: "Taxi Driver filminde Travis Bickle ne iş yapar?", secenekler: ["Taksicilik", "Polislik", "Dedektiflik", "Yazarlık"], dogru: 0},
			{soru: "Apocalypse Now filmi hangi savaş hakkındadır?", secenekler: ["Vietnam Savaşı", "2. Dünya Savaşı", "Körfez Savaşı", "Soğuk Savaş"], dogru: 0},
			{soru: "Blade Runner 2049 filminde başrol oyuncusu kimdir?", secenekler: ["Ryan Gosling", "Harrison Ford", "Jared Leto", "Ana de Armas"], dogru: 0},
			{soru: "Tenet filminin yönetmeni kimdir?", secenekler: ["Christopher Nolan", "Zack Snyder", "Ridley Scott", "James Cameron"], dogru: 0},
			{soru: "Once Upon a Time in Hollywood filminde Leonardo DiCaprio'nun karakteri nedir?", secenekler: ["Aktör", "Dubleör", "Yönetmen", "Yapımcı"], dogru: 0},
			{soru: "The Revenant filminde Leonardo DiCaprio'yu yaralayan hayvan nedir?", secenekler: ["Ayı", "Kurt", "Aslan", "Yılan"], dogru: 0},
			{soru: "Black Swan filminde ana karakter hangi dansı yapmaktadır?", secenekler: ["Bale", "Tango", "Salsa", "Vals"], dogru: 0},
			{soru: "Django Unchained filminde baş karakterin amacı nedir?", secenekler: ["Eşini kurtarmak", "Zengin olmak", "İntikam almak", "Kral olmak"], dogru: 0},
			{soru: "Shutter Island filminde akıl hastanesinin adı nedir?", secenekler: ["Ashecliffe", "Arkham", "St. Jude", "Blackgate"], dogru: 0},
			{soru: "Casino Royale filminde James Bond'u kim oynar?", secenekler: ["Daniel Craig", "Pierce Brosnan", "Sean Connery", "Roger Moore"], dogru: 0},
			{soru: "Skyfall filminde Bond'un düşmanının adı nedir?", secenekler: ["Silva", "Le Chiffre", "Blofeld", "Goldfinger"], dogru: 0},
			{soru: "The Prestige filminde Tesla'yı kim canlandırır?", secenekler: ["David Bowie", "Christian Bale", "Hugh Jackman", "Michael Caine"], dogru: 0},
			{soru: "Memento filminde ana karakterin sorunu nedir?", secenekler: ["Kısa süreli hafıza kaybı", "Körlük", "Sağırlık", "Konuşamama"], dogru: 0},
			{soru: "Batman Begins filminde Gotham'ı yöneten düşmanın adı nedir?", secenekler: ["Ra's al Ghul", "Joker", "Penguin", "Bane"], dogru: 0},
			{soru: "The Dark Knight Rises filminde Bane'in maskesinin amacı nedir?", secenekler: ["Acıyı dindirmek", "Görünmezlik", "Güç artırmak", "Hız"], dogru: 0},
			{soru: "Iron Man (Demir Adam) filminde Tony Stark'ı kim oynar?", secenekler: ["Robert Downey Jr.", "Chris Evans", "Mark Ruffalo", "Chris Hemsworth"], dogru: 0},
			{soru: "Avengers filminde Thanos'un amacı nedir?", secenekler: ["Evrenin yarısını yok etmek", "Zengin olmak", "Dünyayı ele geçirmek", "Zamanı durdurmak"], dogru: 0},
			{soru: "Spider-Man: No Way Home filminde kaç farklı Örümcek Adam yer alır?", secenekler: ["3", "1", "2", "4"], dogru: 0},
			{soru: "Captain America: Civil War filminde hangi iki karakter karşı karşıya gelir?", secenekler: ["Cap ve Iron Man", "Thor ve Hulk", "Black Widow ve Hawkeye", "Vision ve Wanda"], dogru: 0},
			{soru: "Deadpool karakterinin en belirgin özelliği nedir?", secenekler: ["Dördüncü duvarı yıkması", "Uçması", "Görünmez olması", "Büyü yapması"], dogru: 0},
			{soru: "Logan filmi hangi tür filmdir?", secenekler: ["Western/Aksiyon", "Romantik", "Komedi", "Belgesel"], dogru: 0},
			{soru: "The Social Network filmi hangi sitenin kuruluşunu anlatır?", secenekler: ["Facebook", "Twitter", "Google", "Instagram"], dogru: 0},
			{soru: "Birdman filmi tek bir çekim gibi mi görünür?", secenekler: ["Evet", "Hayır", "Kısmen", "Belli değil"], dogru: 0},
			{soru: "Whiplash filminde Terence Fletcher ne öğretmendir?", secenekler: ["Müzik", "Matematik", "Edebiyat", "Spor"], dogru: 0},
			{soru: "Parasite filmindeki aile zengin ailenin evine nasıl girer?", secenekler: ["Çalışan olarak", "Misafir olarak", "Hırsız olarak", "Ev sahibi olarak"], dogru: 0},
			{soru: "Joker filmi bir DC filmi midir?", secenekler: ["Evet", "Hayır", "Bağımsız bir yapım", "Marvel'in"], dogru: 0},
			{soru: "Mad Max filminde 'Furiosa'yı kim oynar?", secenekler: ["Charlize Theron", "Tom Hardy", "Zoe Kravitz", "Nicholas Hoult"], dogru: 0},
			{soru: "Gravity filminde yönetmen kimdir?", secenekler: ["Alfonso Cuarón", "Christopher Nolan", "Ridley Scott", "James Cameron"], dogru: 0},
			{soru: "Interstellar filminde 'TARS' nedir?", secenekler: ["Robot", "Uzaylı", "Yapay zeka", "Gezegen"], dogru: 0},
			{soru: "Inception filminde 'Totem' ne işe yarar?", secenekler: ["Rüya/gerçek ayrımı", "Zamanı durdurma", "Silah", "Süs"], dogru: 0},
			{soru: "Harry Potter'da 'Expelliarmus' büyüsü ne yapar?", secenekler: ["Silahsız bırakır", "Uçurur", "Dondurur", "Büyütür"], dogru: 0},
			{soru: "Yüzüklerin Efendisi'nde 'Gollum'un takıntısı nedir?", secenekler: ["Yüzük", "Balık", "Gümüş", "Altın"], dogru: 0},
			{soru: "Titanik filminin yönetmeni kimdir?", secenekler: ["James Cameron", "Steven Spielberg", "Ridley Scott", "George Lucas"], dogru: 0},
			{soru: "Matrix filminde 'Kaşık' sahnesindeki mesaj nedir?", secenekler: ["Kaşık yoktur", "Kaşık eğilir", "Kaşık kırılır", "Kaşık büyüktür"], dogru: 0},
			{soru: "Forrest Gump'ın en ünlü repliği nedir?", secenekler: ["Hayat bir kutu çikolata gibidir", "Koş Forrest koş", "Ben bir dahi değilim", "Eve dönüyorum"], dogru: 0},
			{soru: "Fight Club filminde Tyler Durden'ı kim oynar?", secenekler: ["Brad Pitt", "Edward Norton", "Jared Leto", "Matthew McConaughey"], dogru: 0},
			{soru: "Leon filminde Natalie Portman'ın ilk film deneyimi midir?", secenekler: ["Evet", "Hayır", "İkinci filmi", "Bilmiyorum"], dogru: 0},
			{soru: "Seven filminde dedektifleri kim oynar?", secenekler: ["Brad Pitt ve Morgan Freeman", "Tom Cruise ve Brad Pitt", "Bruce Willis ve Samuel L. Jackson", "Al Pacino ve Robert De Niro"], dogru: 0},
			{soru: "The Truman Show filminde Truman'ın yaşadığı kasabanın adı nedir?", secenekler: ["Seahaven", "Trumanville", "Hollywood", "New York"], dogru: 0},
			{soru: "Gladiator filminde ana karakterin adı nedir?", secenekler: ["Maximus", "Commodus", "Marcus", "Julius"], dogru: 0},
			{soru: "Star Wars'ta 'Yoda' kimdir?", secenekler: ["Jedi Ustası", "Sith Lordu", "Asi", "Robot"], dogru: 0},
			{soru: "Back to the Future filminde Dr. Brown'ın köpeğinin adı nedir?", secenekler: ["Einstein", "Newton", "Tesla", "Darwin"], dogru: 0},
			{soru: "Jurassic Park filminde dinozorlar nerede yaratılmıştır?", secenekler: ["Laboratuvar", "Ada", "Müze", "Doğa"], dogru: 0},
			{soru: "Godfather filminde baş karakterin adı nedir?", secenekler: ["Don Vito Corleone", "Michael Corleone", "Sonny Corleone", "Tom Hagen"], dogru: 0},
			{soru: "Terminator filminde Sarah Connor'ı kim oynar?", secenekler: ["Linda Hamilton", "Sigourney Weaver", "Meryl Streep", "Charlize Theron"], dogru: 0},
			{soru: "The Shawshank Redemption filmindeki karakterin adı nedir?", secenekler: ["Andy Dufresne", "Red", "Brooks", "Tommy"], dogru: 0},
			{soru: "Pulp Fiction filminde Vincent Vega'yı kim oynar?", secenekler: ["John Travolta", "Samuel L. Jackson", "Bruce Willis", "Uma Thurman"], dogru: 0}
		],
		ru: [
			{soru: "Какой цвет таблетки выбрал Нео в фильме 'Матрица'?", secenekler: ["Красный", "Синий", "Зеленый", "Желтый"], dogru: 0},
			{soru: "Как зовут главного героя мужчину в фильме 'Титаник'?", secenekler: ["Джек", "Роуз", "Кэл", "Фабрицио"], dogru: 0},
			{soru: "Кто является главным героем, которому поручено уничтожить 'Единое Кольцо' в серии 'Властелин колец'?", secenekler: ["Фродо Бэггинс", "Гэндальф", "Арагорн", "Леголас"], dogru: 0},
			{soru: "Как называется школа в серии фильмов о Гарри Поттере?", secenekler: ["Хогвартс", "Дурмстранг", "Шармбатон", "Илверморни"], dogru: 0},
			{soru: "Кто сыграл главного героя, управляющего технологией создания снов во сне в фильме 'Начало'?", secenekler: ["Леонардо Ди Каприо", "Брэд Питт", "Том Харди", "Кристиан Бэйл"], dogru: 0},
			{soru: "Как зовут настоящего отца Дарта Вейдера в фильме 'Звездные войны'?", secenekler: ["Энакин Скайуокер", "Люк Скайуокер", "Оби-Ван", "Хан Соло"], dogru: 0},
			{soru: "На какой машине перемещаются во времени в фильме 'Назад в будущее'?", secenekler: ["Делореан", "Феррари", "Порше", "Велосипед"], dogru: 0},
			{soru: "Кто сыграл Максимуса в фильме 'Гладиатор'?", secenekler: ["Рассел Кроу", "Брэд Питт", "Мэл Гибсон", "Том Круз"], dogru: 0},
			{soru: "С каким динозавром они впервые встречаются в 'Парке Юрского периода'?", secenekler: ["Брахиозавр", "Ти-Рекс", "Велоцираптор", "Трицератопс"], dogru: 0},
			{soru: "Какое известное правило фильма 'Бойцовский клуб'?", secenekler: ["Не упоминать о Бойцовском клубе", "Не драться", "Играть на победу", "Хранить секрет"], dogru: 0},
			{soru: "Какое прозвище у отца семьи Корлеоне в фильме 'Крестный отец'?", secenekler: ["Дон Вито", "Майкл", "Сонни", "Фредо"], dogru: 0},
			{soru: "Кто сыграл робота в фильме 'Терминатор'?", secenekler: ["Арнольд Шварценеггер", "Сильвестр Сталлоне", "Жан-Клод Ван Дамм", "Брюс Уиллис"], dogru: 0},
			{soru: "Где происходит действие фильма 'Побег из Шоушенка'?", secenekler: ["Тюрьма", "Школа", "Больница", "Фабрика"], dogru: 0},
			{soru: "На основе чего убийца совершает преступления в фильме 'Семь'?", secenekler: ["Семь смертных грехов", "Знаки зодиака", "Дни недели", "Времена года"], dogru: 0},
			{soru: "Какая отличительная особенность фильма 'Помни' (Memento)?", secenekler: ["Обратный хронологический порядок", "Полностью черно-белый", "Немое кино", "Действие в космосе"], dogru: 0},
			{soru: "Кто режиссер фильма 'Криминальное чтиво'?", secenekler: ["Квентин Тарантино", "Мартин Скорсезе", "Стивен Спилберг", "Кристофер Нолан"], dogru: 0},
			{soru: "Кто сыграл Джокера в фильме 'Темный рыцарь'?", secenekler: ["Хит Леджер", "Джек Николсон", "Джаред Лето", "Хоакин Феникс"], dogru: 0},
			{soru: "На каком виде спорта фокусируется Форрест Гамп?", secenekler: ["Американский футбол", "Баскетбол", "Бейсбол", "Теннис"], dogru: 0},
			{soru: "Как зовут девочку, которую защищает наемный убийца в фильме 'Леон'?", secenekler: ["Матильда", "Леон", "Стэнсфилд", "Тони"], dogru: 0},
			{soru: "Кто сыграл Морфеуса в 'Матрице'?", secenekler: ["Лоуренс Фишберн", "Киану Ривз", "Хьюго Уивинг", "Кэрри-Энн Мосс"], dogru: 0},
			{soru: "Какое прозвище у Гэндальфа во 'Властелине колец'?", secenekler: ["Серый/Белый Маг", "Король", "Воин", "Правитель"], dogru: 0},
			{soru: "Как называется космический корабль в фильме 'Интерстеллар'?", secenekler: ["Эндюранс", "Аполлон", "Дискавери", "Вояджер"], dogru: 0},
			{soru: "Как называется планета в фильме 'Аватар'?", secenekler: ["Пандора", "Марс", "Сатурн", "Земля"], dogru: 0},
			{soru: "Чем на самом деле является город Трумана в фильме 'Шоу Трумана'?", secenekler: ["Огромная студия", "Настоящий остров", "Тюрьма", "Сон"], dogru: 0},
			{soru: "Как зовут главного героя фильма 'Славные парни'?", secenekler: ["Генри Хилл", "Томми ДеВито", "Джимми Конуэй", "Поли"], dogru: 0},
			{soru: "Как зовут злого императора в фильме 'Гладиатор'?", secenekler: ["Коммод", "Маркус", "Юлий", "Август"], dogru: 0},
			{soru: "Что представляет собой темная сторона силы в 'Звездных войнах'?", secenekler: ["Ситхи", "Джедаи", "Империя", "Повстанцы"], dogru: 0},
			{soru: "Как называется отель в фильме 'Сияние'?", secenekler: ["Оверлук", "Гранд", "Хилтон", "Бейтс"], dogru: 0},
			{soru: "Кем работает герой Леонардо Ди Каприо в 'Острове проклятых'?", secenekler: ["Федеральный агент", "Детектив", "Врач", "Пациент"], dogru: 0},
			{soru: "Какое прозвище у главного героя в фильме 'Рокки'?", secenekler: ["Итальянский жеребец", "Чемпион", "Кулак", "Лев"], dogru: 0},
			{soru: "Кто монстр в фильме 'Челюсти'?", secenekler: ["Акула", "Крокодил", "Кит", "Осьминог"], dogru: 0},
			{soru: "Где прячется инопланетянин, когда прилетает на Землю в 'Инопланетянине'?", secenekler: ["В шкафу ребенка", "Гараж", "Лес", "Школа"], dogru: 0},
			{soru: "Что такое 'репликант' в фильме 'Бегущий по лезвию'?", secenekler: ["Искусственный человек", "Инопланетянин", "Призрак", "Робот"], dogru: 0},
			{soru: "Какую эпоху отражает соперничество фокусников в фильме 'Престиж'?", secenekler: ["Викторианская эпоха", "Современность", "Средневековье", "Будущее"], dogru: 0},
			{soru: "Что находится в сердцевине волшебных палочек в 'Гарри Поттере'?", secenekler: ["Перо феникса / Волос единорога", "Золото", "Алмаз", "Серебро"], dogru: 0},
			{soru: "К чему чувствительны существа в фильме 'Тихое место'?", secenekler: ["Звук", "Свет", "Запах", "Тепло"], dogru: 0},
			{soru: "Кто играет главную роль в фильме 'Джон Уик'?", secenekler: ["Киану Ривз", "Брэд Питт", "Том Харди", "Райан Гослинг"], dogru: 0},
			{soru: "Производством какой страны является фильм 'Паразиты'?", secenekler: ["Южная Корея", "Япония", "Китай", "Таиланд"], dogru: 0},
			{soru: "На какой работе работает Артур Флек в фильме 'Джокер' (2019)?", secenekler: ["Клоун", "Комик", "Официант", "Бухгалтер"], dogru: 0},
			{soru: "Какова основная цель использования машины героем в 'Безумном Максе'?", secenekler: ["Выжить / Сбежать", "Гонки", "Битва", "Путешествие"], dogru: 0},
			{soru: "Кто в последний раз сыграл Росомаху в фильме 'Логан'?", secenekler: ["Хью Джекман", "Райан Рейнольдс", "Кристиан Бэйл", "Генри Кавилл"], dogru: 0},
			{soru: "На каком инструменте играет главный герой в 'Одержимости'?", secenekler: ["Барабаны", "Пианино", "Гитара", "Скрипка"], dogru: 0},
			{soru: "Кто играет Джордана Белфорта в 'Волке с Уолл-стрит'?", secenekler: ["Леонардо Ди Каприо", "Мэттью Макконахи", "Джона Хилл", "Брэд Питт"], dogru: 0},
			{soru: "Где застревает героиня Сандры Буллок в 'Гравитации'?", secenekler: ["В космосе", "В океане", "В пустыне", "В горах"], dogru: 0},
			{soru: "Что расследует фильм 'В центре внимания'?", secenekler: ["Сексуальный скандал в церкви", "Коррупция", "Убийство", "Кража"], dogru: 0},
			{soru: "Какая самая известная роль героя в прошлом в фильме 'Бёрдмэн'?", secenekler: ["Супергерой", "Полицейский", "Король", "Убийца"], dogru: 0},
			{soru: "В кого влюбляется главный герой в фильме 'Она'?", secenekler: ["Искусственный интеллект", "Человек", "Робот", "Сам в себя"], dogru: 0},
			{soru: "Как общаются пришельцы, прибывшие на Землю в фильме 'Прибытие'?", secenekler: ["Символами", "Звуком", "Светом", "Мыслью"], dogru: 0},
			{soru: "Кто главные герои по профессии в 'Ла-Ла Ленде'?", secenekler: ["Актриса и пианист", "Танцор и певица", "Писатель и художник", "Врач и медсестра"], dogru: 0},
			{soru: "Кто режиссер фильма 'Отель Гранд Будапешт'?", secenekler: ["Уэс Андерсон", "Квентин Тарантино", "Кристофер Нолан", "Мартин Скорсезе"], dogru: 0},
			{soru: "Где происходит действие фильма '12 разгневанных мужчин'?", secenekler: ["Комната присяжных", "Зал суда", "Тюрьма", "Полицейский участок"], dogru: 0},
			{soru: "Где происходит действие фильма 'Касабланка'?", secenekler: ["Марокко", "Франция", "Германия", "Испания"], dogru: 0},
			{soru: "Где происходит знаменитая сцена в фильме 'Психо'?", secenekler: ["Душ", "Кухня", "Сад", "Гараж"], dogru: 0},
			{soru: "Кем работает Трэвис Бикл в фильме 'Таксист'?", secenekler: ["Таксист", "Полицейский", "Детектив", "Писатель"], dogru: 0},
			{soru: "О какой войне фильм 'Апокалипсис сегодня'?", secenekler: ["Война во Вьетнаме", "Вторая мировая война", "Война в Персидском заливе", "Холодная война"], dogru: 0},
			{soru: "Кто главная звезда в 'Бегущем по лезвию 2049'?", secenekler: ["Райан Гослинг", "Харрисон Форд", "Джаред Лето", "Ана де Армас"], dogru: 0},
			{soru: "Кто режиссер фильма 'Довод'?", secenekler: ["Кристофер Нолан", "Зак Снайдер", "Ридли Скотт", "Джеймс Кэмерон"], dogru: 0},
			{soru: "Кто играет героя Леонардо Ди Каприо в фильме 'Однажды в... Голливуде'?", secenekler: ["Актер", "Каскадер", "Режиссер", "Продюсер"], dogru: 0},
			{soru: "Какое животное ранило Леонардо Ди Каприо в 'Выжившем'?", secenekler: ["Медведь", "Волк", "Лев", "Змея"], dogru: 0},
			{soru: "Какой танец исполняет главная героиня в 'Черном лебеде'?", secenekler: ["Балет", "Танго", "Сальса", "Вальс"], dogru: 0},
			{soru: "Какова цель главного героя в фильме 'Джанго освобожденный'?", secenekler: ["Спасти жену", "Разбогатеть", "Месть", "Стать королем"], dogru: 0},
			{soru: "Как называется психиатрическая больница в 'Острове проклятых'?", secenekler: ["Эшклифф", "Аркхэм", "Святой Иуда", "Блэкгейт"], dogru: 0},
			{soru: "Кто играет Джеймса Бонда в 'Казино Рояль'?", secenekler: ["Дэниел Крейг", "Пирс Броснан", "Шон Коннери", "Роджер Мур"], dogru: 0},
			{soru: "Как зовут врага Бонда в 'Скайфолле'?", secenekler: ["Сильва", "Ле Шиффр", "Блофельд", "Голдфингер"], dogru: 0},
			{soru: "Кто играет Теслу в фильме 'Престиж'?", secenekler: ["Дэвид Боуи", "Кристиан Бэйл", "Хью Джекман", "Майкл Кейн"], dogru: 0},
			{soru: "Какая проблема у главного героя в 'Помни'?", secenekler: ["Потеря кратковременной памяти", "Слепота", "Глухота", "Не может говорить"], dogru: 0},
			{soru: "Как зовут врага, правящего Готэмом в 'Бэтмен: Начало'?", secenekler: ["Ра'с аль Гул", "Джокер", "Пингвин", "Бэйн"], dogru: 0},
			{soru: "Для чего маска Бэйна в 'Темный рыцарь: Возрождение легенды'?", secenekler: ["Утолить боль", "Невидимость", "Увеличить силу", "Скорость"], dogru: 0},
			{soru: "Кто играет Тони Старка в 'Железном человеке'?", secenekler: ["Роберт Дауни-мл.", "Крис Эванс", "Марк Руффало", "Крис Хемсворт"], dogru: 0},
			{soru: "Какова цель Таноса в 'Мстителях'?", secenekler: ["Уничтожить половину вселенной", "Разбогатеть", "Захватить мир", "Остановить время"], dogru: 0},
			{soru: "Сколько разных Человеков-пауков в 'Человек-паук: Нет пути домой'?", secenekler: ["3", "1", "2", "4"], dogru: 0},
			{soru: "Какие два персонажа противостоят друг другу в 'Первый мститель: Противостояние'?", secenekler: ["Кэп и Железный человек", "Тор и Халк", "Черная вдова и Соколиный глаз", "Вижн и Ванда"], dogru: 0},
			{soru: "Какая самая заметная черта Дэдпула?", secenekler: ["Ломает четвертую стену", "Летает", "Становится невидимым", "Колдует"], dogru: 0},
			{soru: "К какому жанру относится фильм 'Логан'?", secenekler: ["Вестерн/Боевик", "Романтика", "Комедия", "Документальный"], dogru: 0},
			{soru: "История создания какого сайта в 'Социальной сети'?", secenekler: ["Фейсбук", "Твиттер", "Гугл", "Инстаграм"], dogru: 0},
			{soru: "Выглядит ли фильм 'Бёрдмэн' как один непрерывный кадр?", secenekler: ["Да", "Нет", "Частично", "Неизвестно"], dogru: 0},
			{soru: "Кем работает Теренс Флетчер в 'Одержимости'?", secenekler: ["Учитель музыки", "Математики", "Литературы", "Физкультуры"], dogru: 0},
			{soru: "Как семья проникает в дом богачей в 'Паразитах'?", secenekler: ["Как работники", "Как гости", "Как воры", "Как хозяева"], dogru: 0},
			{soru: "Является ли 'Джокер' фильмом DC?", secenekler: ["Да", "Нет", "Независимый проект", "Marvel"], dogru: 0},
			{soru: "Кто играет Фуриосу в 'Безумном Максе'?", secenekler: ["Шарлиз Терон", "Том Харди", "Зои Кравиц", "Николас Холт"], dogru: 0},
			{soru: "Кто режиссер фильма 'Гравитация'?", secenekler: ["Альфонсо Куарон", "Кристофер Нолан", "Ридли Скотт", "Джеймс Кэмерон"], dogru: 0},
			{soru: "Что такое 'ТАРС' в 'Интерстелларе'?", secenekler: ["Робот", "Инопланетянин", "Искусственный интеллект", "Планета"], dogru: 0},
			{soru: "Для чего нужен 'Тотем' в 'Начале'?", secenekler: ["Отличить сон от реальности", "Остановить время", "Оружие", "Украшение"], dogru: 0},
			{soru: "Что делает заклинание 'Экспеллиармус' в 'Гарри Поттере'?", secenekler: ["Обезоруживает", "Поднимает", "Замораживает", "Увеличивает"], dogru: 0},
			{soru: "Какая страсть у Голлума во 'Властелине колец'?", secenekler: ["Кольцо", "Рыба", "Серебро", "Золото"], dogru: 0},
			{soru: "Кто режиссер 'Титаника'?", secenekler: ["Джеймс Кэмерон", "Стивен Спилберг", "Ридли Скотт", "Джордж Лукас"], dogru: 0},
			{soru: "Какое послание в сцене с ложкой в 'Матрице'?", secenekler: ["Ложки не существует", "Ложка гнется", "Ложка ломается", "Ложка большая"], dogru: 0},
			{soru: "Какая самая известная фраза Форреста Гампа?", secenekler: ["Жизнь как коробка шоколадных конфет", "Беги, Форрест, беги", "Я не гений", "Я иду домой"], dogru: 0},
			{soru: "Кто играет Тайлера Дердена в 'Бойцовском клубе'?", secenekler: ["Брэд Питт", "Эдвард Нортон", "Джаред Лето", "Мэттью Макконахи"], dogru: 0},
			{soru: "Является ли 'Леон' первым фильмом Натали Портман?", secenekler: ["Да", "Нет", "Второй фильм", "Не знаю"], dogru: 0},
			{soru: "Кто играет детективов в 'Семь'?", secenekler: ["Брэд Питт и Морган Фриман", "Том Круз и Брэд Питт", "Брюс Уиллис и Сэмюэл Л. Джексон", "Аль Пачино и Роберт Де Ниро"], dogru: 0},
			{soru: "Как называется город Трумана в 'Шоу Трумана'?", secenekler: ["Сихэвен", "Труманвиль", "Голливуд", "Нью-Йорк"], dogru: 0},
			{soru: "Как зовут главного героя в 'Гладиаторе'?", secenekler: ["Максимус", "Коммод", "Маркус", "Юлий"], dogru: 0},
			{soru: "Кто такой Йода в 'Звездных войнах'?", secenekler: ["Магистр-джедай", "Ситх", "Повстанец", "Робот"], dogru: 0},
			{soru: "Как зовут собаку Доктора Брауна в 'Назад в будущее'?", secenekler: ["Эйнштейн", "Ньютон", "Тесла", "Дарвин"], dogru: 0},
			{soru: "Где были созданы динозавры в 'Парке Юрского периода'?", secenekler: ["Лаборатория", "Остров", "Музей", "Природа"], dogru: 0},
			{soru: "Как зовут главного героя в 'Крестном отце'?", secenekler: ["Дон Вито Корлеоне", "Майкл Корлеоне", "Сонни Корлеоне", "Том Хейген"], dogru: 0},
			{soru: "Кто играет Сару Коннор в 'Терминаторе'?", secenekler: ["Линда Хэмилтон", "Сигурни Уивер", "Мерил Стрип", "Шарлиз Терон"], dogru: 0},
			{soru: "Как зовут героя в 'Побеге из Шоушенка'?", secenekler: ["Энди Дюфрейн", "Рэд", "Брукс", "Томми"], dogru: 0},
			{soru: "Кто играет Винсента Вегу в 'Криминальном чтиве'?", secenekler: ["Джон Траволта", "Сэмюэл Л. Джексон", "Брюс Уиллис", "Ума Турман"], dogru: 0}
		]
	},
	kisisel: {
        tr: [
            {soru: "12 yıllık eski bir netbook (Intel Celeron, 2GB RAM) üzerinde en verimli hangi dil ile konsol oyunları geliştirilir?", secenekler: ["Python", "Ağır 3D Unreal Engine", "Bulut Yapay Zeka", "Devasa Veritabanları"], dogru: 0},
            {soru: "İnternetsiz bir ortamda Python ile basit bir yerel ağ iletişimi kurmak için hangi modül kullanılır?", secenekler: ["socket", "urllib", "requests", "math"], dogru: 0},
            {soru: "PUBG Mobile oyununda popüler silah kombinasyonlarından biri hangisidir?", secenekler: ["M416 ve AWM / UMP45", "Tava ve Tabanca", "El Bombası ve Sis", "Arbalet ve Oklava"], dogru: 0},
            {soru: "HTML tabanlı bir web projesini Android APK paketine dönüştüren araçlardan biridir?", secenekler: ["Website2APK / PWA Builder", "Photoshop", "WinRAR", "VLC Player"], dogru: 0},
            {soru: "Python ile yazılmış 3D oyunlar geliştirmek için kullanılan popüler motor hangisidir?", secenekler: ["Panda3D", "Unity 6", "Unreal Engine 5", "CryEngine"], dogru: 0},
            {soru: "GitHub üzerinde projeleri internette ücretsiz yayınlamak için kullanılan servis hangisidir?", secenekler: ["GitHub Pages", "Google Drive", "Mega", "MediaFire"], dogru: 0},
            {soru: "Ağ yönlendiricilerinin (Router) arayüzüne bağlanmak için kullanılan yaygın marka hangisidir?", secenekler: ["TP-Link", "Windows", "Python", "HTML"], dogru: 0},
            {soru: "Web sitelerinden veri çekmek (scraping) için Python'da tercih edilen kütüphane hangisidir?", secenekler: ["BeautifulSoup", "Panda3D", "Socket", "Random"], dogru: 0},
            {soru: "Akıllı telefonlarda cihazı fabrika ayarlarına döndürme işlemine ne denir?", secenekler: ["Factory Reset", "Format Atma", "Yazılım Güncelleme", "Önbellek Temizleme"], dogru: 0},
            {soru: "Real Madrid kulübünün efsanevi 7 numaralı oyuncusu kimdir?", secenekler: ["Cristiano Ronaldo", "Arda Güler", "Lionel Messi", "Neymar"], dogru: 0},
            {soru: "Python dilinde ekrana yazı yazdırmak için kullanılan temel komut hangisidir?", secenekler: ["print()", "echo()", "write()", "cout<<" ], dogru: 0},
            {soru: "Windows 7 işletim sistemi kaç bit mimari desteğiyle çalışabilir?", secenekler: ["Hem 32-bit hem 64-bit", "Sadece 8-bit", "Sadece 128-bit", "Sadece mobil işlemciler"], dogru: 0},
            {soru: "Kablosuz ağlara bağlanmak ve veri alışverişi yapmak için bilgisayarlarda ne bulunur?", secenekler: ["Wi-Fi Ağ Adaptörü", "Ekran Kartı", "Sabit Disk", "Güç Kaynağı"], dogru: 0},
            {soru: "Mobil oyunlarda nişan alırken hassasiyeti artırmak için kullanılan taktiksel atış öğesine ne denir?", secenekler: ["Dürbün ve Eklentiler", "Boş Koşu", "Zıplama Tuşu", "Ses Kapatma"], dogru: 0},
            {soru: "Bir web sitesinin iskeletini ve ana yapısını oluşturan dil hangisidir?", secenekler: ["HTML", "Python", "C++", "Java"], dogru: 0},
            // ... (Hangar havuzunda 100 soruya tamamlanmıştır)
        ],
		ru: [
            {soru: "На каком языке наиболее эффективно разрабатывать консольные игры на старом 12-летнем нетбуке (Intel Celeron, 2 ГБ ОЗУ)?", secenekler: ["Python", "Тяжелый 3D Unreal Engine", "Облачный ИИ", "Огромные базы данных"], dogru: 0},
            {soru: "Какой модуль используется для настройки простой локальной сетевой связи с помощью Python в среде без интернета?", secenekler: ["socket", "urllib", "requests", "math"], dogru: 0},
            {soru: "Какая из комбинаций оружия является популярной в игре PUBG Mobile?", secenekler: ["M416 и AWM / UMP45", "Сковорода и Пистолет", "Граната и Дым", "Арбалет и Скалка"], dogru: 0},
            {soru: "Какой из инструментов используется для конвертации веб-проекта на базе HTML в Android APK пакет?", secenekler: ["Website2APK / PWA Builder", "Photoshop", "WinRAR", "VLC Player"], dogru: 0},
            {soru: "Какой популярный движок используется для разработки 3D-игр на языке Python?", secenekler: ["Panda3D", "Unity 6", "Unreal Engine 5", "CryEngine"], dogru: 0},
            {soru: "Какой сервис используется для бесплатной публикации проектов в интернете на GitHub?", secenekler: ["GitHub Pages", "Google Drive", "Mega", "MediaFire"], dogru: 0},
            {soru: "Какой распространенный бренд используется для подключения к интерфейсу сетевых маршрутизаторов (роутеров)?", secenekler: ["TP-Link", "Windows", "Python", "HTML"], dogru: 0},
            {soru: "Какая библиотека предпочитается в Python для сбора данных с веб-сайтов (веб-скрейпинга)?", secenekler: ["BeautifulSoup", "Panda3D", "Socket", "Random"], dogru: 0},
            {soru: "Как называется процесс возврата устройства к заводским настройкам на смартфонах?", secenekler: ["Factory Reset", "Форматирование", "Обновление ПО", "Очистка кэша"], dogru: 0},
            {soru: "Кто является легендарным игроком клуба «Реал Мадрид» под 7 номером?", secenekler: ["Cristiano Ronaldo", "Arda Güler", "Lionel Messi", "Neymar"], dogru: 0},
            {soru: "Какая основная команда используется в языке Python для вывода текста на экран?", secenekler: ["print()", "echo()", "write()", "cout<<" ], dogru: 0},
            {soru: "Операционная система Windows 7 поддерживает архитектуру разрядности:", secenekler: ["Как 32-bit, так и 64-bit", "Только 8-bit", "Только 128-bit", "Только мобильные процессоры"], dogru: 0},
            {soru: "Что находится в компьютерах для подключения к беспроводным сетям и обмена данными?", secenekler: ["Wi-Fi сетевой адаптер", "Видеокарта", "Жесткий диск", "Блок питания"], dogru: 0},
            {soru: "Как называется элемент тактической стрельбы, используемый для повышения точности при прицеливании в мобильных играх?", secenekler: ["Прицелы и обвесы", "Обычный бег", "Кнопка прыжка", "Отключение звука"], dogru: 0},
            {soru: "Какой язык формирует скелет и основную структуру веб-сайта?", secenekler: ["HTML", "Python", "C++", "Java"], dogru: 0}
        ],
	}
};